---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actualbudget
  namespace: actualbudget
spec:
  interval: 30m
  timeout: 5m
  chart:
    spec:
      chart: actualbudget
      version: 1.8.6
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: actualbudget
      interval: 12h
  values:
    login:
      method: openid
      allowedLoginMethods:
        - openid
      skipSSLVerification: false
      openid:
        enforce: true
        providerName: "Authentik"
        discoveryUrl: "https://authentik.zshen.me/application/o/actual-budget"
        existingSecret:
          name: "actualbudget-secrets-fluxcd"
          clientIdKey: "actualbudget-authentik-client-id"
          clientSecretKey: "actualbudget-authentik-client-secret"

    ingress:
      enabled: true
      className: nginx
      annotations:
        gethomepage.dev/description: A super fast and privacy-focused app for managing your finances. At its heart is the well proven and much loved Envelope Budgeting methodology.
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Applications
        gethomepage.dev/name: ActualBudget
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: budget.zshen.me
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: actualbudget-tls
          hosts:
            - budget.zshen.me

    persistence:
      enabled: true
      storageClass: longhorn
      size: 10Gi
