---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mlflow
  namespace: mlflow
spec:
  interval: 30m
  chart:
    spec:
      chart: mlflow
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: mlflow
      interval: 24h
  dependsOn:
    - name: freshrss-cnpg-cluster
  valuesFrom:
    # externalPostgresql
    - kind: Secret
      name: freshrss-cnpg-cluster-app
      valuesKey: dbname
      targetPath: backendStore.postgres.database
    - kind: Secret
      name: freshrss-cnpg-cluster-app
      valuesKey: host
      targetPath: backendStore.postgres.host
  values:
    ingress:
      enabled: true
      annotations:
        gethomepage.dev/description: The only platform that provides a unified solution for all your AI/ML needs.
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Applications
        gethomepage.dev/name: Mlflow
        kubernetes.io/tls-acme: "true"
      className: nginx
      hosts:
        - host: mlflow.zshen.me
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: mlflow-tls
          hosts:
            - mlflow.zshen.me
    auth:
      enabled: true
      existingAdminSecret:
        name: "mlflow-cnpg-cluster-app"
        usernameKey: "username"
        passwordKey: "password"

    backendStore:
      databaseMigration: false
      databaseConnectionCheck: true
      postgres:
        enabled: true
        # host: "postgresql.postgresql.svc.cluster.local"
        # database: mlflow
      existingDatabaseSecret:
        name: "mlflow-cnpg-cluster-app"
        usernameKey: "username"
        passwordKey: "password"

    # use integrated minio
    artifactRoot:
      s3:
        enabled: true
        bucket: mlflow
        existingSecret:
          keyOfAccessKeyId: minio-user-access-key
          keyOfSecretAccessKey: minio-user-secret-key

    extraEnvVars:
      MLFLOW_S3_ENDPOINT_URL: http://minio-service:9000
      MLFLOW_S3_IGNORE_TLS: "true"
      MLFLOW_SERVER_ALLOWED_HOSTS: "mlflow.zshen.me"

    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5

    serviceMonitor:
      enabled: true
      interval: 30s
      labels:
        release: prometheus

    log:
      enabled: true
      level: info
