apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  valuesFrom:
    - kind: ConfigMap
      name: flux-kube-state-metrics-config
      valuesKey: kube-state-metrics-config.yaml
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    alertmanager:
      enabled: false
    prometheus:
      prometheusSpec:
        retention: 24h
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        podMonitorNamespaceSelector: {}
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring
      ingress:
        enabled: true
        annotations:
          gethomepage.dev/description: Monitor your applications, systems, and services!
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Cluster Monitoring
          gethomepage.dev/icon: prometheus.png
          gethomepage.dev/name: Prometheus
          kubernetes.io/tls-acme: "true"
        ingressClassName: nginx
        hosts:
          - prometheus.monitoring.zshen.me
        tls:
          - secretName: prometheus-tls
            hosts:
              - prometheus.monitoring.zshen.me
    grafana:
      defaultDashboardsEnabled: false
      adminPassword: flux
      ingress:
        enabled: true
        annotations:
          gethomepage.dev/description: Dashboard Waaaaaa!
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Cluster Monitoring
          gethomepage.dev/icon: grafana.png
          gethomepage.dev/name: Grafana
          kubernetes.io/tls-acme: "true"
        ingressClassName: nginx
        hosts:
          - grafana.monitoring.zshen.me
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.monitoring.zshen.me
