---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dify-cnpg-cluster
  namespace: dify
spec:
  interval: 30m
  chart:
    spec:
      chart: cluster
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
      interval: 12h
  values:
    type: postgresql
    version:
      postgresql: "17"
    mode: standalone
    cluster:
      instances: 2 # only two nodes now
      storage:
        size: 5Gi
        storageClass: "longhorn"
      initdb:
        database: dify
        owner: dify_user
      monitoring:
        enabled: true
        podMonitorEnabled: true
    databases:
      - name: dify_plugin
        owner: dify_user
      - name: dify_vector
        owner: dify_user
        extensions:
          - name: vector
            ensure: present
