---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dify
  namespace: dify
spec:
  interval: 30m
  chart:
    spec:
      chart: dify
      version: "0.25.*"
      sourceRef:
        kind: HelmRepository
        name: dify
        namespace: dify
      interval: 12h
  values:
    ingress:
      enabled: true
      annotations:
        gethomepage.dev/description: Production-ready platform for agentic workflow development.
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Applications
        gethomepage.dev/name: Dify
        kubernetes.io/tls-acme: "true"
      className: nginx
      hosts:
        - host: dify.zshen.me
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: dify-tls
          hosts:
            - dify.zshen.me
    api:
      persistence:
        persistenceVolumeClaim:
          storageClass: longhorn
    pluginDaemon:
      persistence:
        persistenceVolumeClaim:
          storageClass: longhorn
    postgresql:
      primary:
        persistence:
          persistenceVolumeClaim:
            storageClass: longhorn
      readReplicas:
        persistence:
          persistenceVolumeClaim:
            storageClass: longhorn
