---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dify
  namespace: dify
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: dify
      version: 0.34.0
      sourceRef:
        kind: HelmRepository
        name: dify
        namespace: dify
      interval: 12h
  valuesFrom:
    - kind: Secret
      name: dify-secrets-flux
      valuesKey: redis-password
      targetPath: externalRedis.password
    - kind: Secret
      name: dify-secrets-flux
      valuesKey: postgresql-username
      targetPath: externalPostgres.username
    - kind: Secret
      name: dify-secrets-flux
      valuesKey: postgresql-password
      targetPath: externalPostgres.password
  values:
    ingress:
      enabled: true
      annotations:
        gethomepage.dev/description: Production-ready platform for agentic workflow development.
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Applications
        gethomepage.dev/name: Dify
        kubernetes.io/tls-acme: "true"
      className: nginx
      hosts:
        - host: chat.zshen.me
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: dify-tls
          hosts:
            - chat.zshen.me
    api:
      persistence:
        persistenceVolumeClaim:
          storageClass: longhorn
    pluginDaemon:
      persistence:
        persistenceVolumeClaim:
          storageClass: longhorn
    postgresql:
      enabled: false
    externalPostgres:
      enabled: true
      address: "postgresql.postgresql.svc.cluster.local"
      database:
        api: "dify"
        pluginDaemon: "dify_plugin"
    redis:
      enabled: false
    externalRedis:
      enabled: true
      host: "redis-master.redis.svc.cluster.local"
      port: 6379
      username: ""
      useSSL: false
