---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    providers:
      longhorn:
        url: https://longhorn.longhorn.svc.cluster.local
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/zhongjis
        - Github/Server-Config:
            - abbr: GH
              href: https://github.com/zhongjis/server-config
        - Github/Nix-Config:
            - abbr: GH
              href: https://github.com/zhongjis/nix-config
    - Tools:
        - ToolTrace:
            - abbr: ToolTrace
              href: https://tooltrace.ai
              description: Gridfinity Bins Gen
        - DupeDotCom:
            - abbr: Dupe
              href: https://dupe.com
              description: Find cheaper alternatives
  services.yaml: |
    - Network:
        - Pi-hole:
            href: http://pihole.home/admin
            description: Homepage is awesome
        - Unifi Network:
            href: http://network.home
            description: Homepage is awesome
    - NAS:
        - TrueNAS:
            href: http://truenas.home
            description: Homepage is the best
    - Applications:
        - Nextcloud:
            href: http://truenas.home:30027
            description: A suite of client-server software for creating and using file hosting services.
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
  proxmox.yaml: ""
