---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage-system
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/zhongjis
  services.yaml: |
    - Network:
        - Pi-hole:
            href: http://pihole.home/admin
            description: Homepage is awesome
        - Unifi Network:
            href: http://network.home/
            description: Homepage is awesome
    - NAS:
        - TrueNAS:
            href: http://truenas.home/
            description: Homepage is the best
    - Applications:
        - Nextcloud:
            href: http://nextcloud.home/
            description: A suite of client-server software for creating and using file hosting services.
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
