apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/actualbudget
  - ../base/authentik/app
  - ../base/cloudflared
  - ../base/freshrss/app
  - ../base/home-assistant
  - ../base/homepage
  - ../base/karakeep
  - ../base/langfuse/app
  - ../base/litellm/app
  - ../base/n8n/app
  - ../base/redis
  - ../base/stirling-pdf
