---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/all.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: n8n-langfuse-shipper
  namespace: n8n
  labels:
    app.kubernetes.io/name: n8n-langfuse-shipper
    app.kubernetes.io/component: sync
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: checkpoint-volume
              emptyDir: {}
          containers:
            - name: shipper
              image: ghcr.io/zhongjis/n8n-langfuse-shipper:latest
              command: ["n8n-shipper", "shipper", "--no-dry-run"]
              envFrom:
                - secretRef:
                    name: n8n-langfuse-shipper-secrets-flux
              env:
                - name: FILTER_AI_ONLY
                  value: "true"
                - name: LANGFUSE_ENV
                  value: "production"
                - name: LOG_LEVEL
                  value: "INFO"
                - name: FETCH_BATCH_SIZE
                  value: "200"
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 1000m
                  memory: 1Gi
              volumeMounts:
                - name: checkpoint-volume
                  mountPath: /data
