apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole-system
spec:
  chart:
    spec:
      chart: mojo2600/pihole
      version: 2.29.1
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
  values:
    # Paste content from pihole.values.yaml here
    image:
      tag: 2025.04.0

    DNS1: 192.168.50.1
    persistentVolumeClaim:
      enabled: true
      storageClass: truenas-nfs

    ingress:
      enabled: true
      ingressClassName: nginx-internal
      hosts:
        - "pihole.home"
      annotations:
        kubernetes.io/ingress.class: "nginx-internal"

    serviceWeb:
      loadBalancerIP: 192.168.50.128
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer

    serviceDns:
      loadBalancerIP: 192.168.50.128
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer

    replicaCount: 1
