apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole-system
spec:
  interval: 1h
  chart:
    spec:
      chart: mojo2600/pihole
      version: 2.29.1
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: pihole-values
