---
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.7.5"
    registry: ghcr.io/fluxcd
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  sync:
    kind: GitRepository
    name: flux-system
    interval: 1m
    url: ssh://git@github.com/zhongjis/server-config
    ref: refs/heads/main
    path: ./flux/clusters/production
    pullSecret: flux-system
  kustomize:
    patches:
      - target:
          group: apps
          version: v1
          kind: Deployment
          name: source-controller
        patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --concurrent=20
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --requeue-dependency=5s
      - target:
          group: apps
          version: v1
          kind: Deployment
          name: kustomize-controller
        patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --concurrent=20
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --requeue-dependency=5s
      - target:
          group: apps
          version: v1
          kind: Deployment
          name: helm-controller
        patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --concurrent=20
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --requeue-dependency=5s
