apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-operator.yaml
  - flux-instance.yaml
  # - weave-gitops.yaml
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: sre-team
