# .sops.yaml

keys:
  - &primary age12x6hk7hpxmemtv8huugzver7mq6xapd42vq899azenrlp77e4sjqcs7745
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *primary
  - path_regex: secrets(/|\\)freshrss.*\.yaml$
    key_groups:
      - age:
          - *primary
  - path_regex: secrets(/|\\)homelab.*\.yaml$
    key_groups:
      - age:
          - *primary
