# .sops.yaml

keys:
  - &primary age12x6hk7hpxmemtv8huugzver7mq6xapd42vq899azenrlp77e4sjqcs7745
  - &homelab age1gff6wle45ktarxc89vfqnq6qawwjcxd5jed4jnuhhddpeqxz6d7q8wq8gn
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *primary
  - path_regex: ^secrets/.*\.yaml$
    key_groups:
      - age:
          - *primary
