---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptimekuma-data
  namespace: uptimekuma
  labels:
    app.kubernetes.io/name: uptimekuma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
