---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik-cnpg-cluster
  namespace: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: cluster
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
      interval: 12h
  values:
    type: postgresql
    version:
      postgresql: "17"
    mode: standalone
    cluster:
      instances: 3
      storage:
        size: 20Gi
        storageClass: "longhorn"
      initdb:
        database: authentik
        owner: authentik_user
      monitoring:
        enabled: true
        podMonitorEnabled: true
