apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/part-of: authentik
    k8s-app: kube-dns
data:
  Corefile: |
    .:53 {
        errors
        health
        ready

        # Custom rewrite for authentik.zshen.me to ingress-nginx-controller
        rewrite name authentik.zshen.me ingress-nginx-controller.nginx-system.svc.cluster.local

        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        cache 30
        loop
        reload
        loadbalance
        import /etc/coredns/custom/*.override
        forward . /etc/resolv.conf
    }
