apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/part-of: authentik
    k8s-app: kube-dns
data:
  Corefile: |
    .:53 {
        errors
        health
        
        # OPTION B: Point to Ingress Controller (Better for SSL)
        # Result: authentik.zshen.me resolves to 10.x.x.x (Ingress Controller ClusterIP)
        rewrite name authentik.zshen.me ingress-nginx-controller.nginx-system.svc.cluster.local answer auto
        
        # (This rule ensures the ANSWER section matches the QUESTION, keeping clients happy)
        # Note: CoreDNS modern versions handle the answer section rewrite automatically for exact matches.
        
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
