---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: pihole-system
spec:
  interval: 1m0s
  url: https://charts.bitnami.com/bitnami

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: externaldns-pihole
  namespace: pihole-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: bitnami/external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: pihole-system
      version: 8.7.11
  values:
    global:
      security:
        allowInsecureImages: true

    image:
      registry: gcr.io
      repository: k8s-staging-external-dns/external-dns
      tag: v20250411-v0.16.1-87-g0d975217

    provider: pihole
    extraArgs:
      pihole-api-version: 6
    policy: upsert-only
    txtOwnerId: "homelab"
    pihole:
      server: http://pihole-web.pihole-system.svc.cluster.local
    extraEnvVars:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole-password
            key: password
    serviceAccount:
      create: true
      name: "external-dns"
    ingressClassFilters:
      - nginx-internal

    logLevel: debug
