---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: langfuse-cnpg-cluster
  namespace: langfuse
spec:
  interval: 30m
  chart:
    spec:
      chart: cluster
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
      interval: 12h
  values:
    type: postgresql
    version:
      postgresql: "18"
    mode: standalone
    cluster:
      instances: 2
      affinity:
        topologyKey: kubernetes.io/hostname
      storage:
        size: 5Gi
        storageClass: "longhorn"
      initdb:
        database: langfuse
        owner: langfuse_user
      monitoring:
        enabled: true
        podMonitorEnabled: true
