# https://github.com/langfuse/langfuse-k8s
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: langfuse
  namespace: langfuse
spec:
  interval: 24h
  url: https://langfuse.github.io/langfuse-k8s
