apiVersion: v1
kind: Secret
metadata:
    name: dify-secrets-flux
    namespace: dify
stringData:
    redis-password: ENC[AES256_GCM,data:GjUDsQ3uHMcA1GUqH6Y=,iv:JoEP8IHfefJAAEQXlI0pRUopOzk/WsMlbigPLFimIY0=,tag:upvjj599VeEfVv/eor/vKQ==,type:str]
    postgresql-username: ENC[AES256_GCM,data:VKaStFIuuXDP2g==,iv:ZgLzfC/kLM2QitSi3K1oTx5bMeLKe96ByOoFdde8cig=,tag:c65UcjwtJe3GcG/XaI99QQ==,type:str]
    postgresql-password: ENC[AES256_GCM,data:RkEWCec29KxclgKomJk=,iv:O61eyt80w5FEy79Y3MMytGwJXCKInpp0JebCbX7YoVw=,tag:amsv3t+9lRBC+CceAthWMg==,type:str]
sops:
    age:
        - recipient: age12x6hk7hpxmemtv8huugzver7mq6xapd42vq899azenrlp77e4sjqcs7745
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydXlsMTZvSDZSb2wxQnV6
            a3dwd0dwaFJ6WFFkSmxMM2xlaWFWelBuL3lNCnk1UW9EamtQTnFINXQvWHlSanA0
            N2lHcjIzdngwWUI4ek5wNXdkK1Z1ZnMKLS0tIHNMRmdGeHNSWnZ5RlVnb1pwcWZW
            bUZZSVNWcmFtRHdnb09HUGxCS1h6Y0UKBu5OAZpqk6Q3AUYVVgalBYSmV5LK7gIM
            3UTVMKnOLHBn553f5s7hEQ5jr8qHPr6sZlSl82yMcGgKJlkYDKnT9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gff6wle45ktarxc89vfqnq6qawwjcxd5jed4jnuhhddpeqxz6d7q8wq8gn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Ry9EcVpTb3IxZURJSGhq
            UDQ3VEQ1dlBJLzllRkE0NVh2MTY3aGxFV2hRCnJlTUlKTlN6TmsybnNBRnZ2dlRY
            bXFuUHlTdENaTnE1QWZxVHRDeTlWUmcKLS0tIHJTNWg5cFFHRVphUUFkdHFZcHVC
            RFNrWktFTFdiNmtZbUd3djNpTkkvb00Ku6ekiYViKRivI7QJNqkxsNk1AYgEwhZ2
            ceyydMfS5apCFFlP5sRTpd0ld6beArjTuYNhG8TT6iU+hsMR1Ig0Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T10:15:02Z"
    mac: ENC[AES256_GCM,data:TgneCgLQI8Vls7DLJv34QfpYYU5H8Jz2/QUbDRuFLL9zIXefrOE4wQd/CVl2/l1lkfWJVYrxVpJEHPEO+ZiWAzk47TOtNDKsSuMSTDxjLnVtfLefjSYKqe6K6UwVj6IqTDV5CnE8B1QPu0E754lFhTdbMe2xrSyow7CR8VIRAyM=,iv:1N9fLt0tX5r6DHhGMbXpf4JSaDntZzHsGa3GoUC6DCU=,tag:lWKXAjyk2VhrdtkxM+AETg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
