apiVersion: v1
kind: Secret
metadata:
    name: freshrss-secrets
    namespace: freshrss
stringData:
    admin-api-password: ENC[AES256_GCM,data:73rXwC8dOSyWfCJdYaw=,iv:sdorv83Ra69d49GT5uesXniUrNgZaztj0PczjRRTIOk=,tag:bIREhQeZAvR2GoWQNMYErg==,type:str]
    admin-password: ENC[AES256_GCM,data:Xo7z4hbUZ2TWGfF19bU=,iv:D9XQHA/xNKK9CY9T9fOHCherZkr8O/1h9NN5eV4Qu7w=,tag:dhijrmMqwDLXUMoG6Vq1Fg==,type:str]
    admin-email: ENC[AES256_GCM,data:DdV5YEGeJxFfzdWOa77ISlkfCaJeB4Lo,iv:vBE0qwIJswdHkgYBIypCX65FTvHmnCQ0UFMVawEdiK0=,tag:WAI+DDssHHkhWr6kmyi2fA==,type:str]
    admin-username: ENC[AES256_GCM,data:8waGWO0=,iv:x+G07TDoXwOAZq2AkS2om6C46zlpPAzcWgt0keqNQDY=,tag:0M3HUIMobpyKWLWPr/F9Vw==,type:str]
    oidc-extraEnvs: ENC[AES256_GCM,data:rH7pZ5WuykyX7wMoB3abu+5pZbjH2JeugwX26/HoNfJ6O3Qr57KSvP4XXIGTd90RI/pC9HqA5ABADUDVDtQJHrEbgkpjpmqioqznzPoDxppNcAnwtMq/jGW1ys3VXvAe666S766hSbl1QcDmx6zuVadiX6FdvzkwHeykvzmevoDf5xNLd2/DPAeAZiyHwMhJjU27c1D9KFDb/Kr9McuJQIXT4PTP8MTjA55pp9gLc1i5jMMBep03xUiwGHCYQgSMz3LdH8tl9m/rYfxADsQKG4HQcltqV9GgHd3h+ak8qubAMfd95NR0Mx+hnZG36PHWqs+IHmZ7pf8eEGTTX2VjU+mmDQYEEwGqmnOqwU7y8rjUEpQBDEBlfXl/N0ctwuoSkroiRkN5GeDl+vvj199viN5j7uK2JroCB5ZIxfgqNbRelntanGz4b06J03sIahZqLTFhD8KDeeof3hoPOyNautWCGZLIvCA95mJloDLcffA4d2NQwyAxOSF/VcFAkwoTkkXG32Yl4TDsR5pxuDODDnO261WLB/21hojnAgA/uh/mzXo+mKJRlO5LD37Zq2rr3NABjwSpniAJeB39JA==,iv:z6c5MWQiSrm2ozLWQaI9xCicDos5N3YcvTyXLuWwz0o=,tag:QNeyRszb6C6+LLUD7Ewm0Q==,type:str]
sops:
    age:
        - recipient: age12x6hk7hpxmemtv8huugzver7mq6xapd42vq899azenrlp77e4sjqcs7745
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydXlsMTZvSDZSb2wxQnV6
            a3dwd0dwaFJ6WFFkSmxMM2xlaWFWelBuL3lNCnk1UW9EamtQTnFINXQvWHlSanA0
            N2lHcjIzdngwWUI4ek5wNXdkK1Z1ZnMKLS0tIHNMRmdGeHNSWnZ5RlVnb1pwcWZW
            bUZZSVNWcmFtRHdnb09HUGxCS1h6Y0UKBu5OAZpqk6Q3AUYVVgalBYSmV5LK7gIM
            3UTVMKnOLHBn553f5s7hEQ5jr8qHPr6sZlSl82yMcGgKJlkYDKnT9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gff6wle45ktarxc89vfqnq6qawwjcxd5jed4jnuhhddpeqxz6d7q8wq8gn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Ry9EcVpTb3IxZURJSGhq
            UDQ3VEQ1dlBJLzllRkE0NVh2MTY3aGxFV2hRCnJlTUlKTlN6TmsybnNBRnZ2dlRY
            bXFuUHlTdENaTnE1QWZxVHRDeTlWUmcKLS0tIHJTNWg5cFFHRVphUUFkdHFZcHVC
            RFNrWktFTFdiNmtZbUd3djNpTkkvb00Ku6ekiYViKRivI7QJNqkxsNk1AYgEwhZ2
            ceyydMfS5apCFFlP5sRTpd0ld6beArjTuYNhG8TT6iU+hsMR1Ig0Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T10:58:08Z"
    mac: ENC[AES256_GCM,data:YBUqpPinAQelKSmbxCwY2D/IcQbXVlivZpeIHqfFJ2pnKfhPHi69dcM/QQIBgvYVcz2WtcyPjkrvSIj1LB0FsKFk34qBwchgC7QQd2LhL7AzFzdk3PDWBpTVJYFtHfZkCUqK2aBNxyeuwewNu+ZODZLCI1RO6g3NCeSDyRq6x7g=,iv:TTzvX01X2+xMS4xwLBvPbV5xIWr1H9Qr036sH4kh6RE=,tag:pbPwWSNoX0CWaTtJj/Ht1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
