apiVersion: v1
kind: Secret
metadata:
    name: gitea-secrets-flux
    namespace: gitea
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:zPNu8kStLgg=,iv:BO5lNpe7/5GfkNNbIUdA7Vnc6+sb1CrG0NrYRrs79a0=,tag:1GrfqEcpefD4N24vPenO4A==,type:str]
    email: ENC[AES256_GCM,data:Fe2O994ExnIxJ0MW+e4homlZAlAve86l,iv:6Yz/XF9wb3f5V1eXdje3gZ0yPnutDCh/6SIyzQsr5b4=,tag:U8qi43FiTqPgqQtPg9qisQ==,type:str]
    password: ENC[AES256_GCM,data:CetjQ0/TKN3ERnX9PDGFR2vKVhBcWpSFz7f4tqaCS9315w++Y64rGGpeRk5j6IDhMOvYg0ziz7QmgSM1znVZsg==,iv:hxAkJ6EL8G9Ubond+L4T6+OjbZrhihoQEQE7MGNkXOQ=,tag:eM1LDkdPqir3rxDsPvlInA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:eP1Pae0Fd/BwNwjCuccMHRGZ1CcsMzpglgTw2H/lWS4yOp0OezhviQUde7BEZwo1XHbhXlX3zEmusilTPvwu/+IbiL5hC04Plg5UimYTn4vN2OTAE2c=,iv:nHzMOp5yFrHi4grO/6qozIpxf7cZiyYpcA97y/yeWuk=,tag:Z/7fgxaR+ajjuMy+m0DDQA==,type:str]
    INTERNAL_TOKEN: ENC[AES256_GCM,data:vaW1xkYeuVBfy52Lf2c17pfCjD6lbsVWc5OnTWaFI79mG5XQs7RgCHSb12M5I6EX5qqHrjO36guAxPpUJdVPRO1jCudlpHcL9oJW/vjwjGKBCj+Jdk0=,iv:um7SJkPwQrsl2zOvVEQ4IH3KsDuMavPO3vA/F2XHTvI=,tag:r8GAVuJ2IHK9dCUuKXbErg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:HnxfFq7Eu447yfJ2z6Ii93nHIG/zeO+VHn0F9T8i47/pl92irOiTkDEZl/SStdWgIbqvmsMEDn+lFbr26CWwsjBQIpHmCyBfllXMAaBGHfNf+gwuuus=,iv:UvR4lfY/WSx+XiRhSe3WE99iTbVcDiFRCgUcDDdomPY=,tag:oqYDOuRzN6KRfQqvQ2g0hg==,type:str]
    LFS_JWT_SECRET: ENC[AES256_GCM,data:PIY5Vp0CHW38ItUwMmHBpD44k4J4/7vDQoNFy+Pu1Ji5IZRFKXA8L54Iqo8Pc32+npGQ1vcE/HNrA37pbWCW3w+Dg2TvQjxXfJo0cckVdsGYwaUmB7M=,iv:54irGibECEskqfG6fElJdHpQK7du8Z6rQlM/KcPzbPk=,tag:fR3TOz4VOZxh0PiKNggXTA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKV1J5SFQ0VWlONjBWdVR6
            R3doUHFsQjRySUVDelF1bjV0OTNKVEkyTzJJCjFFcEE2TlVCOVJ3QlRQclRVTDBw
            MHljaGVpYzNzcENZSkxkUzFwdHRTeUEKLS0tIHQ5UElBcklHL08ydzdldWUvcFJi
            NnFreVIyYjc0UDRKaTBwKzhTelVWbHMKBQdbq/48EW4V8zWkup6smOkscHykabW9
            mYrXGevhn1g8ru2tL1FQ+ArenqKsCvldhvzihvXmDNFOWigbeTwRZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12x6hk7hpxmemtv8huugzver7mq6xapd42vq899azenrlp77e4sjqcs7745
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxd0g0T3dibGtQZTYzVmdm
            SXllNi9xRXczQlBHbmxDcnU2dURWc3Yrckg0CkRBVFRieTMrWExRVUduYmQ2eGtF
            RVB2N2JXeE80WkNMd2k2ekNuVWl2MzAKLS0tIGJza3FIaFpTRmxrVW1QUUVFazFi
            ZnVCS3lqcDMxeC9tMFpZamZLazU3QW8K/hlvJS5+0nF6sYu76p/fGedcP506rliS
            EeiV1HDVOxhb93n/7o/ruujvY4DnVTpRjwd1g2g/ytwMV07XmEOAgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gff6wle45ktarxc89vfqnq6qawwjcxd5jed4jnuhhddpeqxz6d7q8wq8gn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T07:48:43Z"
    mac: ENC[AES256_GCM,data:P3N/AFk6LPeJusmoWbU+RLB0plNL5+IgxbMjIFpmpay5ypNmjMTaOq0/8fxdJeNbeZw1555yi7TcZ1JImEg3DyK5VRZ3UcmGgeTxqOmDLJL18J4hg5DNN51HKKh9Jb1Zi6DUeUQ+7zR0AHCUtcHFvpcGT3nhwLKx/0lI/apRklY=,iv:ShUTGvmQXP8zX6lF/aOwThbRTuazZcGVwcWhVY2pvRk=,tag:no6785Bh6IfTazo8UqzLyg==,type:str]
    version: 3.13.1
