apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secrets-flux
    namespace: karakeep
stringData:
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:u6MNotekqDBPHEFR7jPZDTKGflnI438eRE7IsgU+sszia+ONajBJkg==,iv:qVHpi7I4MM4vkS+wc6IzcMv1Yig4XlKMpjANk7KVKlg=,tag:VzdiWI+5+zlxOmGgR3Fstw==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Sysw+s2KFChm8UDqvHT+mrKNzQ3m/TxSrq8SDbWjwcDvmYmHxdI4UDmCrYIhVxR1tecLrmknkaYbNHurt2uDGTmfD6zO892EKIVDrawxnITbS8ln/QIdtd8v1gRZhISkNgsS4FQdAbpWJiEogpk/MGoY8I6GRNHRsw2GS9v+nkw=,iv:3BIk9o1795SmuzLew2jhRL6PITHT1GQ5SNeoVNqUvDM=,tag:gccNBkk4yJZYjhSI8GmkSA==,type:str]
sops:
    age:
        - recipient: age12x6hk7hpxmemtv8huugzver7mq6xapd42vq899azenrlp77e4sjqcs7745
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydXlsMTZvSDZSb2wxQnV6
            a3dwd0dwaFJ6WFFkSmxMM2xlaWFWelBuL3lNCnk1UW9EamtQTnFINXQvWHlSanA0
            N2lHcjIzdngwWUI4ek5wNXdkK1Z1ZnMKLS0tIHNMRmdGeHNSWnZ5RlVnb1pwcWZW
            bUZZSVNWcmFtRHdnb09HUGxCS1h6Y0UKBu5OAZpqk6Q3AUYVVgalBYSmV5LK7gIM
            3UTVMKnOLHBn553f5s7hEQ5jr8qHPr6sZlSl82yMcGgKJlkYDKnT9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gff6wle45ktarxc89vfqnq6qawwjcxd5jed4jnuhhddpeqxz6d7q8wq8gn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Ry9EcVpTb3IxZURJSGhq
            UDQ3VEQ1dlBJLzllRkE0NVh2MTY3aGxFV2hRCnJlTUlKTlN6TmsybnNBRnZ2dlRY
            bXFuUHlTdENaTnE1QWZxVHRDeTlWUmcKLS0tIHJTNWg5cFFHRVphUUFkdHFZcHVC
            RFNrWktFTFdiNmtZbUd3djNpTkkvb00Ku6ekiYViKRivI7QJNqkxsNk1AYgEwhZ2
            ceyydMfS5apCFFlP5sRTpd0ld6beArjTuYNhG8TT6iU+hsMR1Ig0Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T22:57:42Z"
    mac: ENC[AES256_GCM,data:vyPG4Eu9MIIJGXASlEaB7rOrUR+G6LrUpPJr6egOTZKyG84zzRUx1ytLxWfQIcSqGyLC4mzgsUSgpXDy7IEqpgT/yhnxBeqGvI68r0zDmNAFYY6kqM+eEj3wO5pJC8dcGqeh71G8M2n3ppWIoqcBKLiPWWiFQa5Tn2vyg4XNR6Q=,iv:vv7O8RQRr8jcY8bL4+p0qmSbLjsjQFpqVQJvbddlFJg=,tag:N6hB2d2s1tVdf6lqZUevBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
