apiVersion: v1
kind: Secret
metadata:
    name: langfuse-secrets-flux
    namespace: langfuse
stringData:
    encryptionKey: ENC[AES256_GCM,data:0ukngN9LyjL3Vc9F5X1YClfpJEU7NjqyqQsDzowisDasIuwTI6hnxJVPOMT3HZMxgfY8qiGT7z3WOBNVdIuYFA==,iv:XvoijUzU+lPXub0CiS4/CL4C4pkwkCMrQgsEuArLl3o=,tag:46JRBp2TxKvbCD/O1KVnFQ==,type:str]
    salt: ENC[AES256_GCM,data:bZDkn56ZbFP3YyqwURuaDk0vMxbTfqb9VObgaZ3CWWRmBiBtrdzmL8TSN1g=,iv:avUSqqAyEmjGeFupvOO1GTWvyEsG1PagrHmaUGRbjY8=,tag:J6qCQEjF9iEzjHGlTUPSQA==,type:str]
    nextauth-secret: ENC[AES256_GCM,data:fukO8aYYEC3iqPvFUS///lpQegqww5VppXPSjnLC2RRkWxqmZsGO3Bc0aUw=,iv:/Dy6yQahu2gycEWWINpSorpYOkSNphCUYZ3jb28EiGQ=,tag:k+PP4sTl2JCa6V/3rmj/6g==,type:str]
    clickhouse-user-password: ENC[AES256_GCM,data:pbnbjh60ap0NACgBMpFMOcTnomCXSzLN,iv:fqrdXj7UCv2E3DncVjsKmz0Ob0tIShy1IM5BA6ep0mU=,tag:OY1AWxI8dUEkbw5NYRKr5A==,type:str]
    redis-user-password: ENC[AES256_GCM,data:SvTaf6UswrNVvmWMjkM=,iv:kBUIGOkBERL5u+Kbzk1jdppGc2pc7copzDsTtcEdkF4=,tag:Q91QiCRQIng7mFe3qxxlig==,type:str]
    s3-user-username: ENC[AES256_GCM,data:tN2VW8yBt7k=,iv:loMKPtA69G2B1fbf2x9+LxHU5sjjis21r6uikguWHQM=,tag:gj3+nsAXi7tMZ1KTx5Rl1A==,type:str]
    s3-user-password: ENC[AES256_GCM,data:GnKapqTh4mzSFgrKW0YkxFHr8Kr0GL2A,iv:Yjeq0NRPQ2O38MQm3e0hLrnkINQU9WtAZddGxo17Xfk=,tag:rWEPBjp4zeHvzY549H0qfw==,type:str]
    AUTH_AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:LdNNriIwe2/X1PeJyQrAtxiZoVgDdlBgAYkqkDDY6FuaecF9ZyOR0g==,iv:uqnmlxQ+CrwDcAcCQHX+6DNIdm1oB7/gBghp27NTV0s=,tag:/vzFYXXo6Yxy8J2NpgRc6w==,type:str]
    AUTH_AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:9i/wKXIf+la8ZBzfRjHdJjef5hbNd0CBr5Z3INZlR7m9NGWLPN2m5UOlDqHTlMei1yYDTYM1Ex2ELdabwhblXvhwlvEE/vVTB6d1yZGF0kFoplfmii4Ia9SVwDeLFuhIOMIOJBKcNfUC1DadsQO/qiqu5IoeSGPvR0XwVlL2gnU=,iv:BE9Qr3bAn2VfyrCtlI5YfaVRKteIrpwAGwGH/6MzUpw=,tag:Qzft2eaJfwHosRmAd3YnZw==,type:str]
    AUTH_AUTHENTIK_ISSUER: ENC[AES256_GCM,data:kELJKq9yzliWG80vbgAysxihaiujIXOoYvLgz94EzgG8JjmK1TDGc980koYUWQ/6rMQ=,iv:1QwmwRZ5xagyE9nDVD7/2E5cavvlpAIZbrSTCCcIde8=,tag:Pi3kPNz0z4zvOLEQ4SxJZA==,type:str]
sops:
    age:
        - recipient: age12x6hk7hpxmemtv8huugzver7mq6xapd42vq899azenrlp77e4sjqcs7745
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydXlsMTZvSDZSb2wxQnV6
            a3dwd0dwaFJ6WFFkSmxMM2xlaWFWelBuL3lNCnk1UW9EamtQTnFINXQvWHlSanA0
            N2lHcjIzdngwWUI4ek5wNXdkK1Z1ZnMKLS0tIHNMRmdGeHNSWnZ5RlVnb1pwcWZW
            bUZZSVNWcmFtRHdnb09HUGxCS1h6Y0UKBu5OAZpqk6Q3AUYVVgalBYSmV5LK7gIM
            3UTVMKnOLHBn553f5s7hEQ5jr8qHPr6sZlSl82yMcGgKJlkYDKnT9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gff6wle45ktarxc89vfqnq6qawwjcxd5jed4jnuhhddpeqxz6d7q8wq8gn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Ry9EcVpTb3IxZURJSGhq
            UDQ3VEQ1dlBJLzllRkE0NVh2MTY3aGxFV2hRCnJlTUlKTlN6TmsybnNBRnZ2dlRY
            bXFuUHlTdENaTnE1QWZxVHRDeTlWUmcKLS0tIHJTNWg5cFFHRVphUUFkdHFZcHVC
            RFNrWktFTFdiNmtZbUd3djNpTkkvb00Ku6ekiYViKRivI7QJNqkxsNk1AYgEwhZ2
            ceyydMfS5apCFFlP5sRTpd0ld6beArjTuYNhG8TT6iU+hsMR1Ig0Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T03:51:26Z"
    mac: ENC[AES256_GCM,data:N9iMHR3C4oYijZbaHjU/xOTSPN4+NvlCHbe7xJw5+jnBP9nqgZ0MMiseziTJ2F/xraWXPzD9BzfCapL7+rQrdPZ3iGTXFtt29Q7w+J9VuDO+EsN6z3Hak3y23wpuqhCBHBJN0zqT9A/HVFqrUVW9MJTCFYNOFU8+slW+KIRfItU=,iv:KKusDN05eXDLtZby+UPUTZMsnlBNbsHxV/8CTUO4uO4=,tag:l3kaWJ3bgUE3R0/nkp7u+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
