apiVersion: v1
kind: Secret
metadata:
    name: manyfold-secrets
    namespace: manyfold
stringData:
    postgresql-password: ENC[AES256_GCM,data:s+6enTHOs7Vxrys/2T3H,iv:yhbPXGMu7xjFlZP33qFptL+mnnROHVMuFUHjlbLojQA=,tag:nWxOyZdj8Mnu/0rcURRPGg==,type:str]
    redis-url: ENC[AES256_GCM,data:0cMDbyEP+IzHSWq1ai1UgqjhDa8SoeQ36OV8bw8NfJkk+IN7qDM7NyHqWstuhYoH6j99Ah8duymYYlDYqnhZm5nX+oVBUr4=,iv:m8Ae05+iZeeR8HxSr56WorRoRH3tmIfRQTvEvPqGvPc=,tag:x0g9D52wDEPCWE6IK6vNlw==,type:str]
sops:
    age:
        - recipient: age12x6hk7hpxmemtv8huugzver7mq6xapd42vq899azenrlp77e4sjqcs7745
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydXlsMTZvSDZSb2wxQnV6
            a3dwd0dwaFJ6WFFkSmxMM2xlaWFWelBuL3lNCnk1UW9EamtQTnFINXQvWHlSanA0
            N2lHcjIzdngwWUI4ek5wNXdkK1Z1ZnMKLS0tIHNMRmdGeHNSWnZ5RlVnb1pwcWZW
            bUZZSVNWcmFtRHdnb09HUGxCS1h6Y0UKBu5OAZpqk6Q3AUYVVgalBYSmV5LK7gIM
            3UTVMKnOLHBn553f5s7hEQ5jr8qHPr6sZlSl82yMcGgKJlkYDKnT9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gff6wle45ktarxc89vfqnq6qawwjcxd5jed4jnuhhddpeqxz6d7q8wq8gn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Ry9EcVpTb3IxZURJSGhq
            UDQ3VEQ1dlBJLzllRkE0NVh2MTY3aGxFV2hRCnJlTUlKTlN6TmsybnNBRnZ2dlRY
            bXFuUHlTdENaTnE1QWZxVHRDeTlWUmcKLS0tIHJTNWg5cFFHRVphUUFkdHFZcHVC
            RFNrWktFTFdiNmtZbUd3djNpTkkvb00Ku6ekiYViKRivI7QJNqkxsNk1AYgEwhZ2
            ceyydMfS5apCFFlP5sRTpd0ld6beArjTuYNhG8TT6iU+hsMR1Ig0Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T20:57:57Z"
    mac: ENC[AES256_GCM,data:89iHe8Y81wi90p4/M6FmbmibovCD0rkvWZLJBEFuH1Mzs3a2x0eZ+Bv+3COLRikOsQROhXnZeVkdRZhkrjpVQpfrskA43E4KN023rhgysY8yRixHXS/TQPRjV2vFVQB8u+V2ER4w9xYI2iLelR1chkytMS+EWkh4IT+kRdh5FdE=,iv:PHmLSno9ml8zukn7s4+9hC3mNBXllUkO5ZrdGiIHPTI=,tag:v4hhim14f4oLEa8kZ2k5Ag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
