apiVersion: v1
kind: Secret
metadata:
    name: manyfold-secrets
    namespace: manyfold
stringData:
    postgresql-url: ENC[AES256_GCM,data:V+44cINiAKZJASo0gef1N4acC9eLGtWExfojrwW0KmpdaHRjHr8fS7RPAxJ4liGzFWqphUi/Jac4Wa6WzAKqFsJYFUcsyRotK+X56chzukH/jNq/JuwVFXbUQ8So,iv:7R702kafDHHXPZUKPSqaL61lihg0sp/YgoFvjmE3tqU=,tag:8BJzrqEQyQ4L3i4lOgf/+w==,type:str]
sops:
    age:
        - recipient: age12x6hk7hpxmemtv8huugzver7mq6xapd42vq899azenrlp77e4sjqcs7745
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydXlsMTZvSDZSb2wxQnV6
            a3dwd0dwaFJ6WFFkSmxMM2xlaWFWelBuL3lNCnk1UW9EamtQTnFINXQvWHlSanA0
            N2lHcjIzdngwWUI4ek5wNXdkK1Z1ZnMKLS0tIHNMRmdGeHNSWnZ5RlVnb1pwcWZW
            bUZZSVNWcmFtRHdnb09HUGxCS1h6Y0UKBu5OAZpqk6Q3AUYVVgalBYSmV5LK7gIM
            3UTVMKnOLHBn553f5s7hEQ5jr8qHPr6sZlSl82yMcGgKJlkYDKnT9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gff6wle45ktarxc89vfqnq6qawwjcxd5jed4jnuhhddpeqxz6d7q8wq8gn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Ry9EcVpTb3IxZURJSGhq
            UDQ3VEQ1dlBJLzllRkE0NVh2MTY3aGxFV2hRCnJlTUlKTlN6TmsybnNBRnZ2dlRY
            bXFuUHlTdENaTnE1QWZxVHRDeTlWUmcKLS0tIHJTNWg5cFFHRVphUUFkdHFZcHVC
            RFNrWktFTFdiNmtZbUd3djNpTkkvb00Ku6ekiYViKRivI7QJNqkxsNk1AYgEwhZ2
            ceyydMfS5apCFFlP5sRTpd0ld6beArjTuYNhG8TT6iU+hsMR1Ig0Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-13T22:26:50Z"
    mac: ENC[AES256_GCM,data:5R6NqQaUGMc4lFneLa8sOw7NywjPAFD+SGHTbpAdSbXo8WSfTviMA4yZWD+vI9AJ/Mwj9EbIsbpAaf123jcxaiC4r6BdtdSFTYyQmY6teBiE4kFHQB5THy96rt48LUmKoUE5NR/mNgWCVOslQ16bbd2iZndEHVKo19hHkbmVLv0=,iv:wqs6hO2qYTt9gdHWlmQT821x6KxSPMj59xTAnG8Jcuw=,tag:BTmAuMMCt16fG4eM6H2+6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
