apiVersion: v1
kind: Secret
metadata:
    name: microrealestate-secrets
    namespace: microrealestate
stringData:
    mongo-url: ENC[AES256_GCM,data:jT7TsSDuCxqyOgl7kzgmV0npEVZupeQgUiC5h4i9pBPmNgkq+JIKYRgn8JDZkz9AQCucVkcW9pZuARqUuU3qBXXYd4kGDs8NIfMAHTaPm7wUVd7dAQ==,iv:D6jzruvbLIUeYUVakp2Vj2zSGWWtTY6CJiAmrtWiuuA=,tag:o2iUVdgjwv+n9n8M3K9HWg==,type:str]
    redis-password: ENC[AES256_GCM,data:n7l2bpLg0UC+W7lbThxq,iv:Ye18bSoissGBHAn2BrY8nYUpCYUKNZiq++jfXZkG5as=,tag:0xjHd/li9gy/N5E3x7iq9w==,type:str]
sops:
    age:
        - recipient: age12x6hk7hpxmemtv8huugzver7mq6xapd42vq899azenrlp77e4sjqcs7745
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQzQxNmNvd1NoM3FjMDdl
            dEgydDRSZWI3am52Tng4L1hOam40ZTFjNkhvCms2N0FzWVlPRStpeGxIWkJBYTMv
            eGczNW8yUDdsN0FDcThmUmdJVjhXSEUKLS0tIGFqckVLd21TWHFZRG5CMUxEQVI4
            TnJicDExZG05Y3cyRkhpcGlwVTh3c3MKr+PmP9MoisGwIIMlT8yTfXArALIjMGBq
            qSJ2i6psvQQPDDPhszAcllYsscuG8snSYwCo5K6R84EameEj894rYg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gff6wle45ktarxc89vfqnq6qawwjcxd5jed4jnuhhddpeqxz6d7q8wq8gn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQXNoQk1TRG0yeEE1WWl2
            MU45K0NMckVTQXFQTWM3RTFBSUU0eXdHc1J3CnRtZytWODdscnptczFXNGRURm1U
            aHBPbWQrZmhCaTB0TmdHazlLNnNjdk0KLS0tIFMxWGllM1h3VEhia0EzQm8vYW5V
            OFZoNzNXdjdXSytmeGVLc2xzc0g0clkKggDDnnGiOxPQm6w8ErWnBZc31TW+tpSY
            qToY6hcxG1NmAMsqW4PtpG61BQrdNO0y96mu0OYLdPXVurgtTZ8cVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-14T03:14:02Z"
    mac: ENC[AES256_GCM,data:W0GXxm3VBuWveGfEhXz2Iwx/sv6yqMqH5WZoRd6CbMrpXiyOmp0WHTEt6o4O6UgpJVXEL6QjKQBznG4bvdIptBFokmzuOHboXeVlr2X0N3op7+OKjq2P6eolxHIa4Mxkh0nj+mF3SpS9lCZKJb9n1c4BsuQlYR/4+ZgrizbvRKU=,iv:XeurovyfIMqdeoux343KlxF21h80qAN/7kocb3wVQMk=,tag:4ImGF0X2LPyMA1MbfcNQgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
