apiVersion: v1
kind: Secret
metadata:
    name: microrealestate-secrets
    namespace: microrealestate
stringData:
    mongo-url: ENC[AES256_GCM,data:h9DAdoAEwL42Aua5dmRkmb2s/+Zfsk586+9jaPNl323nU7fTrd/dCKkdCeqOfSOZ3pP30dK9m9koxZoyUxm4g/DVdzXB/XNkLw==,iv:ox1SHR3tfa0FA8aU7leo3h0Boj/bvSd996d7/6Kb5Ok=,tag:WKE/QIHURnUspU5qAAaSAA==,type:str]
sops:
    age:
        - recipient: age12x6hk7hpxmemtv8huugzver7mq6xapd42vq899azenrlp77e4sjqcs7745
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQzQxNmNvd1NoM3FjMDdl
            dEgydDRSZWI3am52Tng4L1hOam40ZTFjNkhvCms2N0FzWVlPRStpeGxIWkJBYTMv
            eGczNW8yUDdsN0FDcThmUmdJVjhXSEUKLS0tIGFqckVLd21TWHFZRG5CMUxEQVI4
            TnJicDExZG05Y3cyRkhpcGlwVTh3c3MKr+PmP9MoisGwIIMlT8yTfXArALIjMGBq
            qSJ2i6psvQQPDDPhszAcllYsscuG8snSYwCo5K6R84EameEj894rYg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gff6wle45ktarxc89vfqnq6qawwjcxd5jed4jnuhhddpeqxz6d7q8wq8gn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQXNoQk1TRG0yeEE1WWl2
            MU45K0NMckVTQXFQTWM3RTFBSUU0eXdHc1J3CnRtZytWODdscnptczFXNGRURm1U
            aHBPbWQrZmhCaTB0TmdHazlLNnNjdk0KLS0tIFMxWGllM1h3VEhia0EzQm8vYW5V
            OFZoNzNXdjdXSytmeGVLc2xzc0g0clkKggDDnnGiOxPQm6w8ErWnBZc31TW+tpSY
            qToY6hcxG1NmAMsqW4PtpG61BQrdNO0y96mu0OYLdPXVurgtTZ8cVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-13T19:48:27Z"
    mac: ENC[AES256_GCM,data:Sj+0h0k68VVxciwwuVpFFOqkbyseyzEbUd9V5dnVC5T6QOT6jG47mWIGYeI+YTcjGZgUQswlUC9KHMBN5wI9kxPHKlKChG3H8S3SLz26+MRXu1H+R0I7ZGwmZ7MlBkFH6a+6KgW2OMP3sQCtfW/cLGZCk0FS4blqJXgO4256MgA=,iv:jnXqMqzgSzwfi/yCGb7NXak0BR7XlBXpURJKMI5uBqM=,tag:IfHaoF+IXD9auEIa0Dvfhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
