apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secrets
    namespace: mongodb
stringData:
    root-password: ENC[AES256_GCM,data:5/N60tStWDGP4rle6KZk,iv:jj7wGnt39ge/cgsHEqFfTNXlu/aOlj25tNVta7UJH7U=,tag:gsVzSwBJniyXjB1Xitl3Bg==,type:str]
    user-passwords:
        fid4sdf1Ifdm: null
sops:
    age:
        - recipient: age12x6hk7hpxmemtv8huugzver7mq6xapd42vq899azenrlp77e4sjqcs7745
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQzQxNmNvd1NoM3FjMDdl
            dEgydDRSZWI3am52Tng4L1hOam40ZTFjNkhvCms2N0FzWVlPRStpeGxIWkJBYTMv
            eGczNW8yUDdsN0FDcThmUmdJVjhXSEUKLS0tIGFqckVLd21TWHFZRG5CMUxEQVI4
            TnJicDExZG05Y3cyRkhpcGlwVTh3c3MKr+PmP9MoisGwIIMlT8yTfXArALIjMGBq
            qSJ2i6psvQQPDDPhszAcllYsscuG8snSYwCo5K6R84EameEj894rYg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gff6wle45ktarxc89vfqnq6qawwjcxd5jed4jnuhhddpeqxz6d7q8wq8gn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQXNoQk1TRG0yeEE1WWl2
            MU45K0NMckVTQXFQTWM3RTFBSUU0eXdHc1J3CnRtZytWODdscnptczFXNGRURm1U
            aHBPbWQrZmhCaTB0TmdHazlLNnNjdk0KLS0tIFMxWGllM1h3VEhia0EzQm8vYW5V
            OFZoNzNXdjdXSytmeGVLc2xzc0g0clkKggDDnnGiOxPQm6w8ErWnBZc31TW+tpSY
            qToY6hcxG1NmAMsqW4PtpG61BQrdNO0y96mu0OYLdPXVurgtTZ8cVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-13T03:52:06Z"
    mac: ENC[AES256_GCM,data:J5IKBeoq314jK8l0NuTLXaEKk86cxoBT47zWOpy8223D1GFiaC86FnkyaS5ZXBSfOY5Zs3zYXCaH102ZZwnznzZ82CXz5W0X6vJecTnpN97iZHa5ig5oEtd0OiM4azRgRqWdSdRiS8NyVNnw493ASG1J2kMYCqxPsUIbk0zFPEU=,iv:nrdpafc7kYRIUnHyhYkcO9ib0RlzeM4lf4XFJhnCcFE=,tag:qp2Cu3/Gy9Zy1KrICZIJmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
