apiVersion: v1
kind: Secret
metadata:
    name: multica-secrets-flux
    namespace: multica
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:FZKwOls9ZwdZ7tdf4aQpiYLWLRg7AH5cPR9aMYCom6YQHaBbuG4OybrPAgnbui8Da7hKXcuS1zanF8m6xdO4RA==,iv:QxYi+BnV9kWAhN5KOx4VV1M8wtvLs/6S44EMUoBX3OU=,tag:yMGYIlnFSH+WccWN6V8Jkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMEE0UTNRSzBpcU9GcVlz
            ajloeU9FVE1EeW9PTnh3OGtOWDg0YnltQVZNCk9IWk93S3ZoblQrNEV3UmdqNldT
            azR5K05JZEUwUFcwRUNycXBVZmpENGMKLS0tIEg4L3NHQVN6T1QrVTQrRFo3Ymt2
            M1J0ZEEwa0U0YlhEZEd0cDgyNjE5ZncKpWMYFGrimqCiygeKnyeEafyqoan0X+Pj
            NXgaypqOtbqaifwHKBW0QrGOUwFji/syd3ap1C0XrM8Q44Fif0qyig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12x6hk7hpxmemtv8huugzver7mq6xapd42vq899azenrlp77e4sjqcs7745
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQ3ZPSjcrcktKYTlTZ2p2
            dGZXTURYQ0ZSTytINDNTb0YraDl4Zmkvc2pJCktpemp2T2h3TUpyR0U0ZkNxNTFP
            dVpwYjBFeVhock13dHpvRXQ1RFpITTQKLS0tIGZuRjRidEpiZlB3ZlpUWkZFSVpx
            YVp5VkUrUlA4RW53Sko5N2pwZmlCL2MKe/DFzP4oGvtno50xH2rjEiL9LKj65VEQ
            EInDKSu9LX2HoLwrVfB7U/mR6dJdGcHOo95e7Y0Gn3ZmdUeg+QcqLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gff6wle45ktarxc89vfqnq6qawwjcxd5jed4jnuhhddpeqxz6d7q8wq8gn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T22:06:07Z"
    mac: ENC[AES256_GCM,data:/ylurWifoliNk5hbCJUuXBjQaQpq60iScH2DFU1VAi1Z+IA+13fhucimbzy0AEeeuhV9BBh3Zx8IYG7/j2i7UM6IbEqakRqJJY62iPkyCkxXfJZQkN/KT3WfGWRLGPyu3sZYtCrDJ5E4HaHkYBXW+b+agYDhWRkXIXUErxBPvmw=,iv:MdSEihy2VNaiXm9F62GSLUAExOQmco+wIlaTUAU8IgA=,tag:zL+JQGA6LVU5ELMD1VQL2A==,type:str]
    version: 3.13.1
