apiVersion: v1
kind: Secret
metadata:
    name: paperclip-secrets-flux
    namespace: paperclip
type: Opaque
stringData:
    #ENC[AES256_GCM,data:9NPiJLKSaZBDCa29QG8GSZPsY46MzdDQGjhZNQEi131GPeyV,iv:isx0fasrSc6AMcdZKfhskLEiji9wG2Zsv5a1Wx1QtBg=,tag:pwQhBie6f4Cdjg4/Qqzsvg==,type:comment]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:orKSAo7MNwg6ZVCWkMnkbqy3yKsaKSJmw4knZ7HbrsVk2qywlKyTAfYj5j7XkhhdNDve0IRhTWJd8qOCRoAExw==,iv:Q3/Zkxf+5kwGY7T7PO0+iSO0hqyoPU0ltTRw4jBhPPw=,tag:U+Jev/WDqb6K5Lzm1P5EEg==,type:str]
sops:
    age:
        - recipient: age12x6hk7hpxmemtv8huugzver7mq6xapd42vq899azenrlp77e4sjqcs7745
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbEcvVjBBTGlwamJrb1pE
            RFhSSENrM3NBTjRKRTFhUE91Uy9iSElqSlg4CjhQZUJ1bEFCeG1zUVlCYkRCZ3Nw
            WXpUa1NzdGdOMDRlTUF5SzRYRm9TTXcKLS0tIFRjTkFXWXQ3UCt6cHpFNU1ESGVu
            WHFEdC80N21zSVZsb2d5SzZ0Y2krUTAKDssoFsaZcBntgNcpzr2xYd8+kSComX9j
            KJrOilaY7M6BIR5odBkWo1/qWSXFgTPMRzk83gV6jykvLtLSUYmzmw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gff6wle45ktarxc89vfqnq6qawwjcxd5jed4jnuhhddpeqxz6d7q8wq8gn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrR2RYZjhWclN5N0ZHZGsz
            K2JGYWtlUWRIU2xqNlYzVGlST09JK1FOZTFFClJXS3hJSkZJaXJzbDNOUStlNUd3
            QmkzaFo2N0F3NzZyb2VHRVZCK1g0Y2cKLS0tIE5FRXdQMzV0TWtFOG95TmlNZ20r
            Mm5qN0FiYTVwS1FEZDBoWTBidFVPVUkKdY1BeAxoVuoG3zwEE1iJy/DHncUH5sLo
            6VYod7LS2iAn4WJAdP/6y9n5YxBS8saE+4PkMtfl8M6o8bQIPObRpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T10:35:59Z"
    mac: ENC[AES256_GCM,data:Q63hxJ02wHEPHadKgRB8kp/mLcH4T9m5bx5PEixcwc8kzdTlnBXItflrVW9hGhS0BVbGGdVkct6aj2M1U8bbX3OFX38wDNxDoazlYTiVrValoNfAj/wY1mJAz8t5YatUaz4PV65F1UtPTUzZYMs7++RfztBOA9XpiBHe+NgPdgU=,iv:mS6adb7xT9rI+qsYZYQ3V1Ty6IHBOHWY/MEpW1JscMI=,tag:7t67cyfPRcolX1LX9M1qhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
