apiVersion: v1
kind: Secret
metadata:
    name: paperclip-secrets-flux
    namespace: paperclip
type: Opaque
stringData:
    #ENC[AES256_GCM,data:9NPiJLKSaZBDCa29QG8GSZPsY46MzdDQGjhZNQEi131GPeyV,iv:isx0fasrSc6AMcdZKfhskLEiji9wG2Zsv5a1Wx1QtBg=,tag:pwQhBie6f4Cdjg4/Qqzsvg==,type:comment]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:orKSAo7MNwg6ZVCWkMnkbqy3yKsaKSJmw4knZ7HbrsVk2qywlKyTAfYj5j7XkhhdNDve0IRhTWJd8qOCRoAExw==,iv:Q3/Zkxf+5kwGY7T7PO0+iSO0hqyoPU0ltTRw4jBhPPw=,tag:U+Jev/WDqb6K5Lzm1P5EEg==,type:str]
    AUTH_AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:46h4DlkvN+GPLrVnmDQ0Ij4psg7QDOHGCUmtIe4ioxCsWgia6uH/XA==,iv:ty7rWgJ+xZ24nFOBLdkQCFaR1dALehKdmGUJ3CBGp0M=,tag:VszN43/TPcZvXayZijKgFw==,type:str]
    AUTH_AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:GfaYOwOvXT0/q5/tWdtR9v9stT8w8Eo7P7chVnKKLEopSbvp4gNIL/IGmRThcoe/GXbiZXQvSxHvT8eyqpQxLFWKoCZYXIm6W/IULPyDPVd4bca/1tE0Vq/lBD6zRWXZzYzMQPe7iE9uhteLlAi0p1sSj1cXNKte9qCjV/gKm4E=,iv:q0w6Q2tm/EEo7HywhFx2fHIdhdqKffrmrdSnnIQxHUU=,tag:uSobDQLi3oi/lg8yqZjxog==,type:str]
    AUTH_AUTHENTIK_ISSUER: ENC[AES256_GCM,data:dneQZlkvJCkiyLu5QJ68C86qikc5eTp+mnYKtYhC2X55f3Szr9Zb5rT8Th/KD7fVGVk=,iv:rstpkA9vVwdGQEKafd+3rLJv5lciMG6J6bsVaAztqt8=,tag:BErqNUHyHLsGXHM6BpDKUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbEcvVjBBTGlwamJrb1pE
            RFhSSENrM3NBTjRKRTFhUE91Uy9iSElqSlg4CjhQZUJ1bEFCeG1zUVlCYkRCZ3Nw
            WXpUa1NzdGdOMDRlTUF5SzRYRm9TTXcKLS0tIFRjTkFXWXQ3UCt6cHpFNU1ESGVu
            WHFEdC80N21zSVZsb2d5SzZ0Y2krUTAKDssoFsaZcBntgNcpzr2xYd8+kSComX9j
            KJrOilaY7M6BIR5odBkWo1/qWSXFgTPMRzk83gV6jykvLtLSUYmzmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12x6hk7hpxmemtv8huugzver7mq6xapd42vq899azenrlp77e4sjqcs7745
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrR2RYZjhWclN5N0ZHZGsz
            K2JGYWtlUWRIU2xqNlYzVGlST09JK1FOZTFFClJXS3hJSkZJaXJzbDNOUStlNUd3
            QmkzaFo2N0F3NzZyb2VHRVZCK1g0Y2cKLS0tIE5FRXdQMzV0TWtFOG95TmlNZ20r
            Mm5qN0FiYTVwS1FEZDBoWTBidFVPVUkKdY1BeAxoVuoG3zwEE1iJy/DHncUH5sLo
            6VYod7LS2iAn4WJAdP/6y9n5YxBS8saE+4PkMtfl8M6o8bQIPObRpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gff6wle45ktarxc89vfqnq6qawwjcxd5jed4jnuhhddpeqxz6d7q8wq8gn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T08:57:28Z"
    mac: ENC[AES256_GCM,data:llfeYCMKjEDTj6kwOb1wMAO5zXvFZJk/C1DZTUolsKPKZLTPqGlB/OiiZzYXsVhgNVmixEjWyvsQ047XvJD8uZziaPuAJPDgk8WTzdrnzxyS+/PW3qtBtCKXJmVPVtrI8quTm7Q6ic41LFTa77ShmyZZqRO1MyiZM7b42w/nF98=,iv:Dnn0Y1g7mpeoK9tUiEtz1r3mXKUXF81iWCU4UqY/ChE=,tag:2nMFnihRFwyijgP5URCcNA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: paperclip-admin
    namespace: paperclip
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:8+6JQxHl3UBjRpMSm2g13fV1HC00JBle,iv:iSQJGhPWAHCDC736A6ebwWhe3v7x0rn2j0F/MU7IX7M=,tag:sKk5B2Rsx4BTcJ0uGN/iEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbEcvVjBBTGlwamJrb1pE
            RFhSSENrM3NBTjRKRTFhUE91Uy9iSElqSlg4CjhQZUJ1bEFCeG1zUVlCYkRCZ3Nw
            WXpUa1NzdGdOMDRlTUF5SzRYRm9TTXcKLS0tIFRjTkFXWXQ3UCt6cHpFNU1ESGVu
            WHFEdC80N21zSVZsb2d5SzZ0Y2krUTAKDssoFsaZcBntgNcpzr2xYd8+kSComX9j
            KJrOilaY7M6BIR5odBkWo1/qWSXFgTPMRzk83gV6jykvLtLSUYmzmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12x6hk7hpxmemtv8huugzver7mq6xapd42vq899azenrlp77e4sjqcs7745
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrR2RYZjhWclN5N0ZHZGsz
            K2JGYWtlUWRIU2xqNlYzVGlST09JK1FOZTFFClJXS3hJSkZJaXJzbDNOUStlNUd3
            QmkzaFo2N0F3NzZyb2VHRVZCK1g0Y2cKLS0tIE5FRXdQMzV0TWtFOG95TmlNZ20r
            Mm5qN0FiYTVwS1FEZDBoWTBidFVPVUkKdY1BeAxoVuoG3zwEE1iJy/DHncUH5sLo
            6VYod7LS2iAn4WJAdP/6y9n5YxBS8saE+4PkMtfl8M6o8bQIPObRpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gff6wle45ktarxc89vfqnq6qawwjcxd5jed4jnuhhddpeqxz6d7q8wq8gn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T08:57:28Z"
    mac: ENC[AES256_GCM,data:llfeYCMKjEDTj6kwOb1wMAO5zXvFZJk/C1DZTUolsKPKZLTPqGlB/OiiZzYXsVhgNVmixEjWyvsQ047XvJD8uZziaPuAJPDgk8WTzdrnzxyS+/PW3qtBtCKXJmVPVtrI8quTm7Q6ic41LFTa77ShmyZZqRO1MyiZM7b42w/nF98=,iv:Dnn0Y1g7mpeoK9tUiEtz1r3mXKUXF81iWCU4UqY/ChE=,tag:2nMFnihRFwyijgP5URCcNA==,type:str]
    version: 3.13.1
