apiVersion: v1
kind: Secret
metadata:
    name: supabase-secrets-flux
    namespace: supabase
stringData:
    jwt-anonKey: ENC[AES256_GCM,data:F2ccBuIyz/W4HIxbXlHzWw3/kyJz6NzgOOlABbtxIWkQmNkOiX3bK6NlAJ2CPuPr3GCatakS41YF9Nu3+O0rbEHK9ltBXaxI7ptucsiW9CQ3+VtaK3OCr+E2fX2kVcj8WZDy7dRxzgzkQcangCkJeJ3vTWGN2nvp3Faa5jp4DJYkZsv00gjKnnbfALj7H7pQlivAshTfN3EovPupsSCb3j006h8gGAu65A==,iv:jkOjRxzVdlbJK55mYECpfucttN8AKsJoIraLUC+9/0o=,tag:IxyOxnIUHcndKd9mL0C3LQ==,type:str]
    jwt-serviceKey: ENC[AES256_GCM,data:9YuAsNopcm4b0NsBRitJ0w6IAl8clSbiFSi7YuFePNuWhiv3PJEyelqFohGQz3ApUCtawnx+/nAl978SF814LHh9QA6I+2i0Mjo7CTEaMLC5YVdKzYdP4fj8svLXBs+dmbOxKeScp5lHXtkpwJrLawCKjKWKQ0Qx6SEGFOul8Zkd+KWQzixxZHuQX+Q15ON1ngbhEZ0aSayd9IvGXyLDBXM8JypaJD/J4Se7DlB75/H6FUWz,iv:e+4ca/hYuqHmNal5Uv+bVCbhH2CH20FyZvFpq26TeTg=,tag:8WME8kkAPGV95GaSl27u7Q==,type:str]
    jwt-secret: ENC[AES256_GCM,data:RS6zKu5MZNlaOjN2csE43ddCmRipJZFd7EL/blHBCC1SpV343K4j3ko6xS0YJSoN6mdjMUvse3FmksRhprV4Ht8eS+3oCcpPGJENDNJmiqi7nUvYuWYWjg==,iv:s8YIiTMRIIB2HUwG1tsMvMZ1kfiaTS/KMfk8vdi5mK8=,tag:JRjPkiD0muCtXrLya38b3Q==,type:str]
    smtp-username: ENC[AES256_GCM,data:imEkRiaHI2ph4VnPV2vX22crAEyXM41v,iv:ER2EIrGs01Vwx9d0RIygTx1upyi4zvPo7Hqd9qqPK8Y=,tag:1cCAmN4ArFQWNym5V7/T6A==,type:str]
    smtp-password: ENC[AES256_GCM,data:FnlP0OKMEgOU,iv:sk+u35PNnO/zmtUXC5MPceKxLBre0jEvtj2ohTGpFjQ=,tag:IyOO4QXST4cZn+k6T3j/kA==,type:str]
    db-password: ENC[AES256_GCM,data:/J5A0hUA5KswPXldoAg=,iv:fth1HthfsEbjNnOWocm3NvB2/AnXnu/84vCKg39f+4Y=,tag:J4IzgRELGkytscF1hYbmdg==,type:str]
    db-database: ENC[AES256_GCM,data:cptGXlRTMKA=,iv:DE/8xzvaQ2UqaJC34F8eKFWtSuIKlAx5Bxn1HDwaOk8=,tag:a1lxwmT6JheuSrpkgKvFYQ==,type:str]
    dashboard-username: ENC[AES256_GCM,data:DbI13q4=,iv:7e2lHtvnjPmAQ3G5Z6do3YJgi5fd3jcCL19ZDvXiedg=,tag:R8lnVMSNK+fPmjmGr8QlGw==,type:str]
    dashboard-password: ENC[AES256_GCM,data:60l4qGM9Q18cCjCZzd0=,iv:IiAEEzvhbPWiqLlrOzpvdiZlDDWqjuwBttSiz0mIeQs=,tag:jautqz9VAB22q3b3akrdpQ==,type:str]
    dashboard-openAiApiKey: ENC[AES256_GCM,data:VIyZXu4nS9oKYs56jblxM4RmGuTE5FfMqvx/f+N1SMZocuDLzqgY+2b4LyWDFsh6f/6jCLWsb2RwjT1AHUsnihTmFdAxw/Zq6hXIjBbFmMLfkv6czVQFr05sek4o/jUyfp1+fabh8UaMSv4QRtIehaHa6JrFA1Gd6yO12UHAVj620GfZFau1D/+9iYIwKQWSslmTp65+BiIVDLpsOxP00Lw6jg4=,iv:+KUKmkfY54nTcrHatBOFMGe3RIAYfZ1uy2emAT4Dxlo=,tag:pi5Ze0vhCDWcwedxaewvkg==,type:str]
    analytics-publicAccessToken: ENC[AES256_GCM,data:iajj/rqykFbWq1mu97G6ddmekXmHb7irLxOA/dbrCm1iMjYM9ApEI3RYMyEBqRZ0f0mLOGVUwPMAZJ/cFANHQY3sjFiN89iitB1QC+nn64yxFMxDO5i1CA==,iv:BsYlfC8Spr8c9VixpCz9Jn3GnngYg6+b+EmLbXMq+IA=,tag:HkMRTyr2JBEyVpxrnCHMGA==,type:str]
    analytics-privateAccessToken: ENC[AES256_GCM,data:jM2IIE/FNk/ITWc6OMC+3OtaOd427z8ndGT0dh5mM5p2Bx+mvewDwYwhb4ksTrLbjAf34eU+0z6oromWpNJGEE8JKeDcWfFxlycu9y3awbbf8PC8EXSXJg==,iv:EQxbomi71iD4We70cO97EXoUJrJ04+8VYnXluf4MV3c=,tag:smWow2Lhuw4bnh95a4ksyQ==,type:str]
    realtime-secretKeyBase: ENC[AES256_GCM,data:YaRLY0OLFBu/Gs/DV6x5/lnRSBE5EDx6aFSPGLdKXz5MDWpwj+MqZSWmuSIicD33Pvja55fAMFt90WxQfMAqpQ==,iv:FfdP2T++cZx5hmvlpeabMwIELXqK8i+cuFesIPUOO/Q=,tag:8mMZHBpm/eLA6zyz/xUeZw==,type:str]
    meta-cryptoKey: ENC[AES256_GCM,data:dTouzP9Ah5JmP91FH2CHsjAVWtqo3o/non5dRnUCFY4=,iv:W0C8lmzrZnMuwUL1yC6edAcLDlJpw6Z+O0ciihDVO4g=,tag:XGvGBN4rfaFGLcfput94xA==,type:str]
sops:
    age:
        - recipient: age12x6hk7hpxmemtv8huugzver7mq6xapd42vq899azenrlp77e4sjqcs7745
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydXlsMTZvSDZSb2wxQnV6
            a3dwd0dwaFJ6WFFkSmxMM2xlaWFWelBuL3lNCnk1UW9EamtQTnFINXQvWHlSanA0
            N2lHcjIzdngwWUI4ek5wNXdkK1Z1ZnMKLS0tIHNMRmdGeHNSWnZ5RlVnb1pwcWZW
            bUZZSVNWcmFtRHdnb09HUGxCS1h6Y0UKBu5OAZpqk6Q3AUYVVgalBYSmV5LK7gIM
            3UTVMKnOLHBn553f5s7hEQ5jr8qHPr6sZlSl82yMcGgKJlkYDKnT9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gff6wle45ktarxc89vfqnq6qawwjcxd5jed4jnuhhddpeqxz6d7q8wq8gn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Ry9EcVpTb3IxZURJSGhq
            UDQ3VEQ1dlBJLzllRkE0NVh2MTY3aGxFV2hRCnJlTUlKTlN6TmsybnNBRnZ2dlRY
            bXFuUHlTdENaTnE1QWZxVHRDeTlWUmcKLS0tIHJTNWg5cFFHRVphUUFkdHFZcHVC
            RFNrWktFTFdiNmtZbUd3djNpTkkvb00Ku6ekiYViKRivI7QJNqkxsNk1AYgEwhZ2
            ceyydMfS5apCFFlP5sRTpd0ld6beArjTuYNhG8TT6iU+hsMR1Ig0Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T08:07:30Z"
    mac: ENC[AES256_GCM,data:mXFIRDrqfA+nHE/Bo+RDCVqbIMP8377mNAjP3DQTjnTUi/+HF7FISO+9g1FeSJE7qo/rPVB6Km+ZqJVDw1/b5Tv2SZSW3rJtasoQklfJp8VVmHLO+JjmnuAs4+ct17G6QuXigeIOUEVOYLbxXB4A317R/nCpHLIDRual6nwqjfU=,iv:dnS21ArvucA2THeY4BDKQrNZRQ+YpxGcvHx1E2GDq8c=,tag:HGsf7AbWtDzLiEfj2Y+92A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
