---
apiVersion: v1
kind: Namespace
metadata:
  name: agent-sandbox-system

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: agent-sandbox
  namespace: agent-sandbox-system
spec:
  interval: 12h
  url: https://github.com/kubernetes-sigs/agent-sandbox
  ref:
    tag: v0.4.6

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agent-sandbox
  namespace: agent-sandbox-system
spec:
  interval: 30m
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: agent-sandbox
        namespace: agent-sandbox-system
      interval: 12h
  values:
    image:
      tag: v0.4.6
    namespace:
      create: false
      name: agent-sandbox-system
    controller:
      extensions: false
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
