---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 24h
  url: https://cloudnative-pg.io/charts/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 30m0s
  chart:
    spec:
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cnpg-operator
        namespace: cnpg-system
      version: 0.27.0
values:
  monitoring:
    podMonitorEnabled: true
    grafanaDashboard:
      create: true
      namespace: monitoring
