# NOTE: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring-system
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 75.*.*
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring-system
      interval: 12h
  values:
    alertmanager:
      ingress:
        enabled: true
        annotations:
          gethomepage.dev/description: Prometheus AlertManager
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Cluster Monitoring
          gethomepage.dev/icon: alertmanager.png
          gethomepage.dev/name: AlertManager
        ingressClassName: nginx
        hosts:
          - alertmanager.monitoring.home
    grafana:
      ingress:
        enabled: true
        annotations:
          gethomepage.dev/description: Dashboard Waaaaaa!
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Cluster Monitoring
          gethomepage.dev/icon: grafana.png
          gethomepage.dev/name: Grafana
        ingressClassName: nginx
        hosts:
          - grafana.monitoring.home
    prometheus:
      ingress:
        enabled: true
        annotations:
          gethomepage.dev/description: Monitor your applications, systems, and services!
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Cluster Monitoring
          gethomepage.dev/icon: prometheus.png
          gethomepage.dev/name: Prometheus
        ingressClassName: nginx
        hosts:
          - prometheus.monitoring.home
