---
apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
  labels:
    toolkit.fluxcd.io/tenant: sre-team

---
# NOTE: https://artifacthub.io/packages/helm/bitnami/postgresql
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: 12h
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    semver: 16.7.15

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: postgresql
    namespace: postgresql
  values:
    existingSecret: postgresql-secrets
