csiDriver:
  name: "iscsi"

storageClasses:
  - name: truenas-iscsi
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: xfs
      detachedVolumesFromSnapshots: "false"
    mountOptions: []
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

driver:
  config:
    driver: freenas-iscsi
    instance_id:
    httpConnection:
      protocol: http
      host: 192.168.50.102
      port: 80
      username: root # Use your FreeNAS admin username
      # TODO: replace this
      apiKey:
      allowInsecure: true
      apiVersion: 2
    sshConnection: # Add this section
      host: 192.168.50.102
      port: 22
      username: root
      # TODO: ssh-keygen -t rsa -C root@truenas.home -f truenas_rsa
      privateKey: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        -----END OPENSSH PRIVATE KEY-----
    zfs:
      datasetParentName: zimablade-rack-pool/kube/iscsi/v
      detachedSnapshotsDatasetParentName: zimablade-rack-pool/kube/iscsi/s
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
    iscsi:
      targetPortal: "192.168.50.102:3260"
      targetPortals: []
      interface:
      namePrefix: csi-
      nameSuffix: "-clustera"
      targetGroups:
        - targetGroupPortalGroup: 2
          targetGroupInitiatorGroup: 1
          targetGroupAuthType: None
          targetGroupAuthGroup:
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 512
      extentRpm: "SSD"
      extentAvailThreshold: 0
