global:
  security:
    allowInsecureImages: true

image:
  registry: gcr.io
  repository: k8s-staging-external-dns/external-dns
  tag: v20250411-v0.16.1-87-g0d975217
provider: pihole
extraArgs:
  pihole-api-version: 6
policy: upsert-only
txtOwnerId: "homelab"
pihole:
  server: http://pihole-web.pihole-system.svc.cluster.local
extraEnvVars:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-password
        key: password
serviceAccount:
  create: true
  name: "external-dns"
ingressClassFilters:
  - nginx-internal

logLevel: debug
