# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/all.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflared
      version: 2.0.8
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: default
      interval: 12h

  valuesFrom:
    # Tunnel secrets (replace with your encoded values)
    - kind: Secret
      name: cloudflared-secrets
      valuesKey: config-json-base64
      targetPath: tunnelSecrets.base64EncodedConfigJsonFile
    - kind: Secret
      name: cloudflared-secrets
      valuesKey: cert-pem-base64
      targetPath: tunnelSecrets.base64EncodedPemFile

  values:
    # Tunnel configuration
    tunnelConfig:
      name: "homelab-k8s"
      logLevel: "info"
      protocol: "auto"
      retries: 5
      connectTimeout: "30s"
      gracePeriod: "30s"

    # Ingress rules
    # ingress:
    #   - hostname: zshen.me
    #     service: http://your-service.namespace.svc.cluster.local:80
    #   - service: http_status:404

    replica:
      allNodes: true
