---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: redis
    namespace: redis
  values:
    auth:
      enabled: true
      existingSecret: redis-secrets
      existingSecretPasswordKey: redis-password
    metrics:
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 384Mi
      serviceMonitor:
        enabled: true
