---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: redis
    namespace: redis
  suspend: true
  values:
    image:
      digest: "sha256:a267ca7184a768d589e04a40cb0706181ab6e736ec79161a14f973230bec8783"
    architecture: standalone
    master:
      persistence:
        existingClaim: redis-data-recovery
    auth:
      enabled: true
      existingSecret: redis-secrets
      existingSecretPasswordKey: redis-password
    metrics:
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 384Mi
      serviceMonitor:
        enabled: true
