---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: redis
    namespace: redis
  values:
    auth:
      enabled: true
      existingSecret: redis-secrets
      existingSecretPasswordKey: redis-password
