---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freshrss-cnpg-cluster
  namespace: freshrss
spec:
  interval: 30m
  chart:
    spec:
      chart: cluster
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
      interval: 12h
  values:
    type: postgresql
    version:
      postgresql: "17"
    mode: standalone
    cluster:
      instances: 2 # only two nodes now
      storage:
        size: 5Gi
        storageClass: "longhorn"
      bootstrap:
        initdb:
          database: freshrss
          owner: freshrss_user
      monitoring:
        enabled: true
        podMonitorEnabled: true
