---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freshrss
  namespace: freshrss
spec:
  interval: 30m
  chart:
    spec:
      chart: freshrss
      version: "1.1.*"
      sourceRef:
        kind: HelmRepository
        name: christianhuth
        namespace: freshrss
      interval: 12h
  values:
    service:
      type: LoadBalancer
    ingress:
      enabled: true
      annotations:
        gethomepage.dev/description: FreshRSS is a self-hosted RSS and Atom feed aggregator. It is lightweight, easy to work with, powerful, and customizable.
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Applications
        gethomepage.dev/name: FreshRSS
      className: nginx
      hosts:
        - host: rss.home
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
      #  - secretName: chart-example-tls
      #    hosts:
      #      - dify-example.local
