---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freshrss
  namespace: freshrss
spec:
  interval: 30m
  chart:
    spec:
      chart: freshrss
      version: "1.1.*"
      sourceRef:
        kind: HelmRepository
        name: christianhuth
        namespace: freshrss
      interval: 12h
  values:
    ingress:
      annotations:
        gethomepage.dev/description: FreshRSS is a self-hosted RSS and Atom feed aggregator. It is lightweight, easy to work with, powerful, and customizable.
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Applications
        gethomepage.dev/name: FreshRSS
      className: nginx
      hosts:
        - host: rss.home
          paths:
            - path: /
              pathType: ImplementationSpecific
        # - host: dify-example2.local
        #   paths:
        #     - path: /
        #       pathType: Prefix
      tls: []
      #  - secretName: chart-example-tls
      #    hosts:
      #      - dify-example.local
    api:
      persistence:
        persistenceVolumeClaim:
          storageClass: longhorn
    pluginDaemon:
      persistence:
        persistenceVolumeClaim:
          storageClass: longhorn
    postgresql:
      primary:
        persistence:
          persistenceVolumeClaim:
            storageClass: longhorn
      readReplicas:
        persistence:
          persistenceVolumeClaim:
            storageClass: longhorn
