# https://github.com/christianhuth/helm-charts/tree/main/charts/freshrss
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: christianhuth
  namespace: freshrss
spec:
  interval: 24h
  url: https://charts.christianhuth.de
