---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-controller
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/infra/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-resources
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/cluster/homelab/metallb-system/resource
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: metallb-controller
  wait: true
