---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    email: jasonshen96115@gmail.com
    # The server is replaced in /clusters/production/infrastructure.yaml
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
      - dns01:
        cloudflare:
          email: jasonshen96115@gmail.com
          apiTokenSecretRef:
            name: cert-manager-secrets
            key: cloudflare-api-token
