---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-langfuse-shipper-checkpoint
  namespace: n8n
  labels:
    app.kubernetes.io/name: n8n-langfuse-shipper
    app.kubernetes.io/component: checkpoint-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
