apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cattle-system
  - ./flux-system
  - ./longhorn-system
  - ./nginx-system
  - ./metallb-controller.yaml
  - ./metallb-resource.yaml
