# https://github.com/christianhuth/helm-charts/tree/main/charts/freshrss
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 24h
  url: https://helm.openwebui.com/
