# https://github.com/christianhuth/helm-charts/tree/main/charts/freshrss
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio
  namespace: minio
spec:
  interval: 24h
  url: https://operator.min.io/
