# https://github.com/minio/operator/tree/master/helm/operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio
  namespace: minio-operator
spec:
  interval: 24h
  url: https://operator.min.io/
