apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: cloudflared
data:
    tunnel-token-base64: ENC[AES256_GCM,data:RVbuNDy2rg0xVbal+tR5rkyOXLkeS3yJlsRi5u+21KCmSZlUXn5ZN7pO38DKy2QoT4HXlI5MJfiv+cgM5sf3PBTpYIDyUpQgBCwJTMBqeonzi77Fe9t0ZddsULeht9+hYL+FV6asnZo/OkIpu21uynDoo3K6UhMho+xEg2r0jgvN6uqYXRYpElF57b9xexMnUMVYPpBp+sL1t1ORPL8PdTUf97zn4le3jO7gkTibCaZHTeS9EueW8KFRB6jwjXqul1OXcftKZ/9eHcdRM88XEt73SkKQtwg/9vKGcaiFUZujPh5abkuGl9iTzgZFkinWhVB6TH+clm8=,iv:0jbici5FkjTKP5MlLan4dMUSmCo3OCOyWKx3Yf3+4X4=,tag:1mwme9D6qt5BKtRdTcYfWA==,type:str]
sops:
    age:
        - recipient: age12x6hk7hpxmemtv8huugzver7mq6xapd42vq899azenrlp77e4sjqcs7745
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOWpaZjBTUE1Qai9ERDFm
            Tit2M1RWV3VJb1hsTnBQZjlOU0FINmtyc1hjCjFYR1ErajFsVmI3Y1hFamhNKzY5
            dG1FYWZDc1ZjQzR3bWp6QURYbEZIUlkKLS0tIDkwaXpVQlRucFVFdG56VGY3YWNr
            NWRuMUozVHJMblRXZ01Ma2VwdnJ5VlkKulk5U0NTTCC4fhXub5iUicylWPKrhwxX
            /WGYc+TPOIAK5uLZUCY0/TZTpFVf8vVhdxSsdq1jUrJ89PDfJtDO2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gff6wle45ktarxc89vfqnq6qawwjcxd5jed4jnuhhddpeqxz6d7q8wq8gn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVHo2SjRPTTRnS3p2eVJr
            dkNyci9FVDZFSjdEVFM2K3QwcW1sSkQ3Ymd3Cnh3ZDdYNTl6Uy9DZ0Fpdm1nbVdl
            NkQwTGxKd0NodFZKRDFIaTFudThUakUKLS0tIEE1ZXUzMkpMejViTDZvYmNxSTUw
            Vjc0WWVoSUdocUpTd3kzd204RG90bFEKaC5GwFNQbYSaFaJ8Ty/s7qdRlx0/gBqo
            yyb/uXS1t6INxOVFzp7d5R7UsYTqRDS8GEPWJJbLYSsbEFi6PBhPQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-06T01:45:25Z"
    mac: ENC[AES256_GCM,data:LNuDkYnN8ad9RryW7WStN7XZBanRfxfrv5gePSok4Ls4E6x/q7waU7FsvKXa28AHhsFPpM8eBK3Wp1dZDRJ9unrK6zWi+zlUJ7TI5bbVtJ47kwfXRknBksfkSuN4dLG2fDl/Wqv6wejiYfpdgB7VuWCVrq8MtuQ7mg+Lwfz13fM=,iv:Dbb/cmpvlONFc7Sl8DwCIcm+qm04Pv8VUT8Ej27AtjE=,tag:9DCHvfRK3yHPR4QP1QwGgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
