apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: cloudflared
stringData:
    tunnel-token-base64: ENC[AES256_GCM,data:Nz8WC41Kq2ZBY6GWNYRneSbLCUHmc/QCo14+iDfw+EqAuSDD3lDlo2LcF1mZzpkdB2cZfhH2G2GxKIouY4S7FhY7/1MxrvQ9k+c8IemQ58WcVu9v0Cf3MWP3A1EKyyOQaO3wIYF+mW2lWubrH2fu7ZIXr2i2O4SMvMPgF99f950eOE4nNIYfmmaFKxxGclAEmnudP9KPCwgR6DbBcDJb+4lBcCdJCe/2HQptdcXBD3uSSmtnrPThrD5+FvbKYJFTn4yvubQTUyFrvBjsUXayx95jJOpnZI4qxbCz/TasJowE6qGy1ObhDSowELraEVNLF0ZS2WQ1vaA=,iv:NTs5sssnq1Not8boWPFmPHcC6DAe51w/LN852OOAWO8=,tag:j67yNndsaFqRGHtxu2W9Lg==,type:str]
sops:
    age:
        - recipient: age12x6hk7hpxmemtv8huugzver7mq6xapd42vq899azenrlp77e4sjqcs7745
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOWpaZjBTUE1Qai9ERDFm
            Tit2M1RWV3VJb1hsTnBQZjlOU0FINmtyc1hjCjFYR1ErajFsVmI3Y1hFamhNKzY5
            dG1FYWZDc1ZjQzR3bWp6QURYbEZIUlkKLS0tIDkwaXpVQlRucFVFdG56VGY3YWNr
            NWRuMUozVHJMblRXZ01Ma2VwdnJ5VlkKulk5U0NTTCC4fhXub5iUicylWPKrhwxX
            /WGYc+TPOIAK5uLZUCY0/TZTpFVf8vVhdxSsdq1jUrJ89PDfJtDO2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gff6wle45ktarxc89vfqnq6qawwjcxd5jed4jnuhhddpeqxz6d7q8wq8gn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVHo2SjRPTTRnS3p2eVJr
            dkNyci9FVDZFSjdEVFM2K3QwcW1sSkQ3Ymd3Cnh3ZDdYNTl6Uy9DZ0Fpdm1nbVdl
            NkQwTGxKd0NodFZKRDFIaTFudThUakUKLS0tIEE1ZXUzMkpMejViTDZvYmNxSTUw
            Vjc0WWVoSUdocUpTd3kzd204RG90bFEKaC5GwFNQbYSaFaJ8Ty/s7qdRlx0/gBqo
            yyb/uXS1t6INxOVFzp7d5R7UsYTqRDS8GEPWJJbLYSsbEFi6PBhPQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-06T01:31:51Z"
    mac: ENC[AES256_GCM,data:7315Ncy0LkndwFWKyy8LN7ku48cXla/W0fYij5Pun9TMZ1sTWL2t968oJLAcVRSkdzxi3Gq9P7oBbQjLCR0OrKrpcw0rUsV5kQs16Sx4NFOHG7jeswpywmAgV9bAXtuhts3EdPX78cGhqqU6UIGGHvI7hrYpZlXVSW+FxrPxxoU=,iv:/81ZgB9AosTo2pqFfCAHZmlzWcMYIhse+dln1HZ5T1s=,tag:qShXbjQlNzq/T+m+rVYIfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
