apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secrets
    namespace: external-dns
type: Opaque
data:
    pihole-password: ENC[AES256_GCM,data:kqDNl+M=,iv:1b4dgz6U5JEfjOtSa61A3ZoeQuObo9jOAabGohbl+aM=,tag:m+yy3s1ESn+umCz5c9TCSQ==,type:str]
sops:
    age:
        - recipient: age1gff6wle45ktarxc89vfqnq6qawwjcxd5jed4jnuhhddpeqxz6d7q8wq8gn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WXUydS82bVlJV0NlWmhH
            SFFSRTc1cG90TVR3ZHFTSW5GUDBUcEVmaVJnCldPR1lOZjhDOUxaOEp1NmNabk0z
            azBKdHMyS3gvT2JYWVBnZDA4a25uMmcKLS0tIHB2dmJxS1NTSmRZR1paeTgzRmpm
            WnBETHVEVWJrNG5UenlsZ3QyMTduM0EKj25bP9MVARiaqbcYxWZvL2S8lMxZwjZS
            nYLw36UOOaQUYV1EBFjZzevxuIl4jR0VI5j3YDP3u5Aq+9in2m9dDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T02:22:47Z"
    mac: ENC[AES256_GCM,data:/BRselgo9QeeaQAnkliIYNmVxQ53HLp7QPVFrmwKeooUnpnONErokpHdUAveptQyhVs5RYRrIUpKzbe4UP1elNkQ6IuwnOqRn1x8W3MLPRpYEHx2ZcMGg2Bht6Cm5wUa9e4x4mWCl/BYU2IwrkLScejppgR6EaC+9UtzJCuQito=,iv:6EM6bShh+s1TYGMYH9XlgkAUOzO5xEED/OJC+kqup4U=,tag:JM5fPjJeUr9KERY9yTobxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
