---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: metallb/metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
      version: 0.14.9
