---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: supabase
  namespace: supabase
spec:
  interval: 24h
  timeout: 20m
  chart:
    spec:
      chart: charts/supabase
      sourceRef:
        kind: GitRepository
        name: supabase
        namespace: supabase
      interval: 12h

  values:
    secret:
      jwt:
        secretRef: supabase-secrets-flux
        secretRefKey:
          anonKey: jwt-anonKey
          serviceKey: jwt-serviceKey
          secret: jwt-secret
      db:
        secretRef: supabase-secrets-flux
        secretRefKey:
          username: db-username
          password: db-password
          database: db-database
      smtp:
        secretRef: supabase-secrets-flux
        secretRefKey:
          username: smtp-username
          password: smtp-password
      dashboard:
        secretRef: supabase-secrets-flux
        secretRefKey:
          username: dashboard-username
          password: dashboard-password
      analytics:
        secretRef: supabase-secrets-flux
        secretRefKey:
          apiKey: analytics-apiKey
    kong:
      image:
        repository: kong
        tag: 3.9.1
    auth:
      image:
        repository: supabase/gotrue
        tag: v2.143.0
    rest:
      image:
        repository: postgrest/postgrest
        tag: v12.2.0
    storage:
      image:
        repository: supabase/storage-api
        tag: v0.48.0
    realtime:
      image:
        repository: supabase/realtime
        tag: v2.30.0
    meta:
      image:
        repository: supabase/postgres-meta
        tag: v0.75.0
    functions:
      image:
        repository: supabase/edge-runtime
        tag: v1.55.0
    studio:
      image:
        repository: supabase/studio
        tag: v0.24.0
    db:
      image:
        repository: supabase/postgres
        tag: 15.1.0.139
      ingress:
        enabled: true
        annotations:
          gethomepage.dev/description: Postgres development platform.
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Backend
          gethomepage.dev/name: Supabase
          kubernetes.io/tls-acme: "true"
        className: nginx
        hosts:
          - host: supabase.zshen.me
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: supabase-tls
            hosts:
              - supabase.zshen.me
