---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: supabase
  namespace: supabase
spec:
  interval: 24h
  url: https://github.com/luizfelmach/supabase-kubernetes
  ref:
    branch: feature/supabase-2025
