---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: supabase
  namespace: supabase
spec:
  interval: 24h
  timeout: 20m
  chart:
    spec:
      chart: charts/supabase
      sourceRef:
        kind: GitRepository
        name: supabase
        namespace: supabase
      interval: 12h
  values:
    secret:
      jwt:
        secretRef: "supabase-secrets-flux"
        secretRefKey:
          anonKey: jwt-anonKey
          serviceKey: jwt-serviceKey
          secret: jwt-secret
      db:
        secretRef: "supabase-secrets-flux"
        secretRefKey:
          password: db-password
          database: db-database
      smtp:
        secretRef: "supabase-secrets-flux"
        secretRefKey:
          username: smtp-username
          password: smtp-password
      analytics:
        secretRef: "supabase-secrets-flux"
        secretRefKey:
          publicAccessToken: analytics-publicAccessToken
          privateAccessToken: analytics-privateAccessToken
      dashboard:
        secretRef: "supabase-secrets-flux"
        secretRefKey:
          username: dashboard-username
          password: dashboard-password
          openAiApiKey: dashboard-openAiApiKey
      realtime:
        secretRef: "supabase-secrets-flux"
        secretRefKey:
          secretKeyBase: realtime-secretKeyBase
      meta:
        secretRef: "supabase-secrets-flux"
        secretRefKey:
          cryptoKey: meta-cryptoKey
      s3:
        secretRef: "supabase-secrets-flux"
        secretRefKey:
          keyId: minio-key-id
          accessKey: minio-access-key

    db:
      enabled: true
      image:
        tag: 15.8.1.085
      livenessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
        initialDelaySeconds: 3
      persistence:
        enabled: true
      nodeSelector:
        kubernetes.io/hostname: homelab-0

    studio:
      image:
        tag: 2025.11.10-sha-5291fe3
      environment:
        DEFAULT_ORGANIZATION_NAME: Default Organization
        DEFAULT_PROJECT_NAME: Default Project
        SUPABASE_PUBLIC_URL: http://supabase.zshen.me
        NEXT_PUBLIC_ENABLE_LOGS: true
      nodeSelector:
        kubernetes.io/hostname: homelab-0

    auth:
      image:
        tag: v2.182.1
      environment:
        API_EXTERNAL_URL: http://supabase.zshen.me
        GOTRUE_SITE_URL: http://supabase.zshen.me
        GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
        GOTRUE_MAILER_AUTOCONFIRM: "true"
        GOTRUE_SMTP_ADMIN_EMAIL: "your-mail@supabase.zshen.me"
        GOTRUE_SMTP_HOST: "smtp.supabase.zshen.me"
        GOTRUE_SMTP_PORT: "587"
        GOTRUE_SMTP_SENDER_NAME: "your-mail@supabase.zshen.me"
      nodeSelector:
        kubernetes.io/hostname: homelab-0

    rest:
      image:
        tag: v13.0.7
      nodeSelector:
        kubernetes.io/hostname: homelab-0

    realtime:
      image:
        tag: v2.63.0
      livenessProbe:
        httpGet:
          path: /
          port: 4000
        initialDelaySeconds: 3
      nodeSelector:
        kubernetes.io/hostname: homelab-0

    meta:
      image:
        tag: v0.93.1
      nodeSelector:
        kubernetes.io/hostname: homelab-0

    storage:
      image:
        tag: v1.29.0
      livenessProbe:
        httpGet:
          path: /status
          port: 5000
        initialDelaySeconds: 3
      persistence:
        enabled: true
      environment:
        # Set S3 endpoint if using external object-storage
        # GLOBAL_S3_ENDPOINT: http://minio:9000
        STORAGE_BACKEND: s3
        GLOBAL_S3_PROTOCOL: http
        GLOBAL_S3_FORCE_PATH_STYLE: true
        AWS_DEFAULT_REGION: stub
      nodeSelector:
        kubernetes.io/hostname: homelab-0

    imgproxy:
      image:
        tag: v3.8.0
      environment:
        IMGPROXY_ENABLE_WEBP_DETECTION: "true"
      livenessProbe:
        exec:
          command:
            - imgproxy
            - health
        initialDelaySeconds: 3
      persistence:
        enabled: false
      nodeSelector:
        kubernetes.io/hostname: homelab-0

    kong:
      image:
        repository: kong
        tag: 2.8.1
      environment:
        KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
        KONG_LOG_LEVEL: info
      ingress:
        enabled: true
        className: "nginx"
        annotations:
          gethomepage.dev/description: Postgres development platform.
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Backend
          gethomepage.dev/name: Supabase
          kubernetes.io/tls-acme: "true"
        tls:
          - secretName: supabase-tls
            hosts:
              - supabase.zshen.me
        hosts:
          - host: supabase.zshen.me
            paths:
              - path: /
                pathType: Prefix
      nodeSelector:
        kubernetes.io/hostname: homelab-0

    analytics:
      image:
        tag: 1.22.6
      livenessProbe:
        httpGet:
          path: /health
          port: 4000
        initialDelaySeconds: 3
      nodeSelector:
        kubernetes.io/hostname: homelab-0

    vector:
      image:
        tag: 0.28.1-alpine
      livenessProbe:
        httpGet:
          path: /health
          port: 9001
        initialDelaySeconds: 3
      ## Vector requires logs from the control plane to function.
      ## This is normally stored in /var/log/pods
      ## Modify these values according to your environment.
      volumeMounts:
        - name: pod-logs
          mountPath: /var/log/pods
      volumes:
        - name: pod-logs
          hostPath:
            path: /var/log/pods
      nodeSelector:
        kubernetes.io/hostname: homelab-0

    functions:
      image:
        tag: v1.68.4
      nodeSelector:
        kubernetes.io/hostname: homelab-0

    # minio
    minio:
      enabled: true
      image:
        repository: minio/minio
        pullPolicy: IfNotPresent
        tag: "latest"
      replicaCount: 1
      persistence:
        enabled: true
        storageClassName: "longhorn"
        size: 10Gi
        accessModes:
          - ReadWriteOnce
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 100
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80
