---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: supabase
  namespace: supabase
spec:
  interval: 24h
  url: https://github.com/zhongjis/supabase-kubernetes
  ref:
    branch: main
