---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: supabase
  namespace: supabase
spec:
  interval: 24h
  timeout: 20m
  chart:
    spec:
      chart: charts/supabase
      sourceRef:
        kind: GitRepository
        name: supabase
        namespace: supabase
      interval: 12h

  valuesFrom:
    # JWT
    - kind: Secret
      name: supabase-secrets-flux
      valuesKey: jwt-anonKey
      targetPath: secret.jwt.anonKey
    - kind: Secret
      name: supabase-secrets-flux
      valuesKey: jwt-serviceKey
      targetPath: secret.jwt.serviceKey
    - kind: Secret
      name: supabase-secrets-flux
      valuesKey: jwt-secret
      targetPath: secret.jwt.secret

    # SMTP
    - kind: Secret
      name: supabase-secrets-flux
      valuesKey: smtp-username
      targetPath: secret.smtp.username
    - kind: Secret
      name: supabase-secrets-flux
      valuesKey: smtp-password
      targetPath: secret.smtp.password

    # dashboard
    - kind: Secret
      name: supabase-secrets-flux
      valuesKey: dashboard-username
      targetPath: secret.dashboard.username
    - kind: Secret
      name: supabase-secrets-flux
      valuesKey: dashboard-password
      targetPath: secret.dashboard.password
    - kind: Secret
      name: supabase-secrets-flux
      valuesKey: dashboard-openai-api-key
      targetPath: secret.dashboard.openAiApiKey

    # database
    # - kind: Secret
    #   name: supabase-secrets-flux
    #   valuesKey: db-database
    #   targetPath: secret.db.database
    # - kind: Secret
    #   name: supabase-secrets-flux
    #   valuesKey: db-password
    #   targetPath: secret.db.password

    # analytics
    - kind: Secret
      name: supabase-secrets-flux
      valuesKey: analytics-public-access-token
      targetPath: secret.analytics.publicAccessToken
    - kind: Secret
      name: supabase-secrets-flux
      valuesKey: analytics-private-access-token
      targetPath: secret.analytics.privateAccessToken

    # realtime
    - kind: Secret
      name: supabase-secrets-flux
      valuesKey: realtime-secret-key-base
      targetPath: secret.realtime.secretKeyBase

    # realtime
    - kind: Secret
      name: supabase-secrets-flux
      valuesKey: meta-crypto-key
      targetPath: secret.meta.cryptoKey

  values:
    secret:
      db:
        secretRef: "supabase-secrets-flux"
        secretRefKey:
          password: db-password
          database: db-database
    db:
      enabled: true
      image:
        tag: 15.8.1.085
      livenessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
        initialDelaySeconds: 3
      persistence:
        enabled: true

    studio:
      image:
        tag: 2025.11.10-sha-5291fe3
      environment:
        DEFAULT_ORGANIZATION_NAME: Default Organization
        DEFAULT_PROJECT_NAME: Default Project
        SUPABASE_PUBLIC_URL: http://supabase.zshen.me
        NEXT_PUBLIC_ENABLE_LOGS: true

    auth:
      image:
        tag: v2.182.1
      environment:
        API_EXTERNAL_URL: http://supabase.zshen.me
        GOTRUE_SITE_URL: http://supabase.zshen.me
        GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
        GOTRUE_MAILER_AUTOCONFIRM: "true"
        GOTRUE_SMTP_ADMIN_EMAIL: "your-mail@supabase.zshen.me"
        GOTRUE_SMTP_HOST: "smtp.supabase.zshen.me"
        GOTRUE_SMTP_PORT: "587"
        GOTRUE_SMTP_SENDER_NAME: "your-mail@supabase.zshen.me"

    rest:
      image:
        tag: v13.0.7

    realtime:
      image:
        tag: v2.63.0
      livenessProbe:
        httpGet:
          path: /
          port: 4000
        initialDelaySeconds: 3

    meta:
      image:
        tag: v0.93.1

    storage:
      image:
        tag: v1.29.0
      livenessProbe:
        httpGet:
          path: /status
          port: 5000
        initialDelaySeconds: 3
      persistence:
        enabled: false

    imgproxy:
      image:
        tag: v3.8.0
      environment:
        IMGPROXY_ENABLE_WEBP_DETECTION: "true"
      livenessProbe:
        exec:
          command:
            - imgproxy
            - health
        initialDelaySeconds: 3
      persistence:
        enabled: false

    kong:
      image:
        repository: kong
        tag: 2.8.1
      environment:
        KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
        KONG_LOG_LEVEL: info
      ingress:
        enabled: true
        className: "nginx"
        annotations:
          gethomepage.dev/description: Postgres development platform.
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Backend
          gethomepage.dev/name: Supabase
          kubernetes.io/tls-acme: "true"
        tls:
          - secretName: supabase-tls
            hosts:
              - supabase.zshen.me
        hosts:
          - host: supabase.zshen.me
            paths:
              - path: /
                pathType: Prefix

    analytics:
      image:
        tag: 1.22.6
      livenessProbe:
        httpGet:
          path: /health
          port: 4000
        initialDelaySeconds: 3

    vector:
      image:
        tag: 0.28.1-alpine
      livenessProbe:
        httpGet:
          path: /health
          port: 9001
        initialDelaySeconds: 3
      ## Vector requires logs from the control plane to function.
      ## This is normally stored in /var/log/pods
      ## Modify these values according to your environment.
      volumeMounts:
        - name: pod-logs
          mountPath: /var/log/pods
      volumes:
        - name: pod-logs
          hostPath:
            path: /var/log/pods

    functions:
      image:
        tag: v1.68.4
