apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: tempo
      version: 1.24.3
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h

  # https://github.com/grafana/helm-charts/tree/main/charts/tempo
  # values:
