apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sentry
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: sentry
      version: v27.10.0
      sourceRef:
        kind: HelmRepository
        name: sentry
        namespace: monitoring
      interval: 12h

  # https://github.com/sentry-kubernetes/charts
  # values:
