---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: postgresql
    namespace: postgresql

  values:
    auth:
      username: user
      existingSecret: postgresql-secrets
      secretKeys:
        adminPasswordKey: admin-password
        userPasswordKey: user-password
        replicationPasswordKey: replication-password
      database: "manyfold"
    metrics:
      enabled: true
