---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: postgresql
    namespace: postgresql

  values:
    global:
      defaultStorageClass: longhorn
      postgresql:
        auth:
          username: user
          existingSecret: postgresql-secrets
          secretKeys:
            adminPasswordKey: admin-password
            userPasswordKey: user-password
            replicationPasswordKey: replication-password
          database: "manyfold"
    persistence:
      enabled: true
      # volumeName: "data"
      # existingClaim: "data-postgresql-0"
      # mountPath: /bitnami/postgresql
      # subPath: ""
      storageClass: longhorn
      accessModes:
        - ReadWriteOnce
      size: 10Gi
    metrics:
      enabled: true
