---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: mongodb
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: postgresql
    namespace: postgresql

  values:
    auth:
      user: user
      existingSecret: postgresql-secrets
      secretKeys:
        adminPasswordKey: admin-password
        userPasswordKey: user-password
        replicationPasswordKey: replication-password
    metrics:
      enabled: true
