---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: 12h
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    semver: "16.7.15"
