# NOTE: https://artifacthub.io/packages/helm/jeffresc/manyfold
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: manyfold
  namespace: manyfold
spec:
  interval: 30m
  chart:
    spec:
      chart: manyfold
      # version: 0.1.6
      sourceRef:
        kind: HelmRepository
        name: jeffresc
        namespace: manyfold
      interval: 12h
  valuesFrom:
    - kind: Secret
      name: manyfold-secrets
      valuesKey: postgresql-url
      targetPath: env.DATABASE_URL
  values:
    ingress:
      enabled: true
      annotations:
        gethomepage.dev/description: A self-hosted digital asset manager for 3d print files.
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Applications
        gethomepage.dev/name: Manyfold
        kubernetes.io/tls-acme: "true"
      className: nginx
      hosts:
        - host: manyfold.zshen.me
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: manyfold-tls
          hosts:
            - manyfold.zshen.me
    redis:
      enabled: true
    persistence:
      enabled: true
    env:
      PUID: "1000"
      PGID: "1000"
      REDIS_URL: redis://redis.redis.svc.cluster.local:6379/1
