# NOTE: https://artifacthub.io/packages/helm/jeffresc/manyfold
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: manyfold
  namespace: manyfold
spec:
  interval: 30m
  chart:
    spec:
      chart: manyfold
      # version: 0.1.6
      sourceRef:
        kind: HelmRepository
        name: jeffresc
        namespace: manyfold
      interval: 12h
  valuesFrom:
    - kind: Secret
      name: manyfold-secrets
      valuesKey: postgresql-password
      targetPath: env.DATABASE_PASSWORD.value
    - kind: Secret
      name: manyfold-secrets
      valuesKey: redis-url
      targetPath: env.REDIS_URL.value
  values:
    serviceAccount:
      create: true
      name: default
    ingress:
      enabled: true
      annotations:
        gethomepage.dev/description: A self-hosted digital asset manager for 3d print files.
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Applications
        gethomepage.dev/name: Manyfold
        kubernetes.io/tls-acme: "true"
      className: nginx
      hosts:
        - host: manyfold.zshen.me
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: manyfold-tls
          hosts:
            - manyfold.zshen.me
    redis:
      enabled: false
    postgresql:
      enabled: false
    persistence:
      enabled: true
      size: 15Gi
      storageClass: "longhorn"
    env:
      # REDIS_URL:
      #   value: "redis://rfG%2AGbpOp%259a8NI@redis-master.redis.svc.cluster.local:6379/1"
      DATABASE_ADAPTER:
        value: "postgresql"
      DATABASE_HOST:
        value: "postgresql.postgresql.svc.cluster.local"
      DATABASE_PORT:
        value: "5432"
      DATABASE_USER:
        value: "user"
      # DATABASE_PASSWORD:
      #   value: "{{ .Values.postgresql.global.postgresql.auth.password }}"
      DATABASE_NAME:
        value: "manyfold"
      PUID:
        value: 1000
      PGID:
        value: 1000
