---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: mongodb
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: mongodb
    namespace: mongodb

  values:
    auth:
      enabled: true
      rootUser: root
      # FIXME: single user secrets never works
      # usernames:
      #   - microrealestate
      # databases:
      #   - mredb # NOTE: for microrealestate
      existingSecret: mongodb-secrets
    metrics:
      enabled: true
      username: "metricuser"
    # passwordUpdateJob:
    #   enabled: true
    #   previousPasswords:
    #     existingSecret: mongodb-secrets
