---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: mongodb
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: mongodb
    namespace: mongodb

  valuesFrom:
    - kind: Secret
      name: microrealestate-secrets
      valuesKey: root-password
      targetPath: auth.rootPassword
    - kind: Secret
      name: microrealestate-secrets
      valuesKey: user-passwords
      targetPath: auth.passwords

  values:
    passwordUpdateJob:
      enabled: true
    usernames:
      - microrealestate
    databases:
      - mredb
