---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: mongodb
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: mongodb
    namespace: mongodb
