---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: mongodb
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: mongodb
    namespace: mongodb

  values:
    auth:
      enabled: true
      rootUser: root
      usernames:
        - microrealestate
      databases:
        - mredb # NOTE: for microrealestate
      existingSecret: mongodb-secrets
      passwordUpdateJob:
        enabled: true
    metrics:
      enabled: true
