---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: mongodb
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: mongodb
    namespace: mongodb

  valuesFrom:
    - kind: Secret
      name: mongodb-secrets
      valuesKey: root-password
      targetPath: auth.rootPassword
    - kind: Secret
      name: mongodb-secrets
      valuesKey: user-passwords
      targetPath: auth.passwords

  values:
    passwordUpdateJob:
      enabled: true
    usernames:
      - microrealestate
    databases:
      - mredb

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongodb
  namespace: mongodb
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: mongodb.zshen.me
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: mongodb
                port:
                  number: 27017
  tls:
    - secretName: mongodb-tls
      hosts:
        - mongodb.zshen.me
