---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mongodb
  namespace: mongodb
spec:
  interval: 12h
  url: oci://registry-1.docker.io/bitnamicharts/mongodb
  ref:
    semver: "16.5.x"
